<?php 
	$title = "Steven Johnson";
	$section = "podcasts";
	include("../includes/header.inc.php"); 
?>

<div class="container clear">
	<div class="secondary">
		<ul class="speakers">
			<li><h2><a href="/schedule/StevenJohnson.php" class="speak2">Steven Johnson</a></h2></li>
			<li><a href="/schedule/AleksKrotoski.php" class="speak3">Aleks Krotoski</a></li>
			<li><a href="/schedule/DanielBurka.php" class="speak4">Daniel Burka</a></li>
			<li><a href="/schedule/MattJones.php" class="speak5">Matt Jones</a></li>
			<li><a href="/schedule/MattBiddulph.php" class="speak6">Matt Biddulph</a></li>
			<li><a href="/schedule/JoshuaPorter.php" class="speak7">Joshua Porter</a></li>
			<li><a href="/schedule/JeremyKeith.php" class="speak8">Jeremy Keith</a></li>
			<li><a href="/schedule/TantekCelik.php" class="speak9">Tantek Celik</a></li>
		</ul>
	</div>
	<div class="primary transcript">
	<h2>The Urban Web</h2>
		<p class="transcript_credit"><a href="http://opera.com"><img src="/img/sponsors/opera.gif" alt="Opera Software" /></a>
		Transcription sponsored by <a href="http://www.opera.com/">Opera</a>.</p>
		
		<blockquote>
		<p> Thank you! This is really exciting. It&#8217;s an honor to open up the show here today. I&#8217;m Steven Johnson. I thought what I would do is talk a little bit about the past and then talk a little bit about the future. I thought it was appropriate, as any good interaction-designed conference should, to start the day with Cholera, in part because I think the story I want to talk about which is based on the story of my last book, The Ghost Map, has a lot of relevance to our particular point today, particularly with reference to the growing geographic web that a lot of us are involved in building out and also because it&#8217;s a great way to start the morning, with a rousing speech about intestinal disease. So, it just seems to me the preppy way to begin.</p>
            <p>So, I want to take us back to London in 1854. The largest city in the world, the largest city the world had ever seen and a city that was literally mired in its own filth. It was an incredibly disgusting place to live in 1854. Just to entertain you, I&#8217;ll read one quote here from the kind of social historian and journalist, Henry Mayhew.</p>
            <p>He wrote in 1851, visiting a site of a Cholera outbreak, &quot;As we passed along the reeking banks of the sewer, the sun shone upon a narrow slip of the water. In the bright light, it appeared the color of strong green tea and possibly looked as solid as black marble in the shadow. Indeed, it was more like watery mud than muddy water. And yet we were assured this was the only water the wretched inhabitants had to drink.&quot;</p>
            <p>&quot;As we gazed in horror at it, we saw drains and sewers emptying their filthy contents into it, we saw a whole tier of doorless privies in the open road common to men and women built over it, we heard bucket after bucket splashed into it and the limbs of the vagrant boys bathing in it seemed by pure force of contrast, white as marble.&quot;</p>
            <p>This is the kind of stuff they left out of the masterpiece theatre vision of London in the Victorian era, right? This was everyday life and what it created, what you basically had here was a Victorian city living within Elizabethian public health infrastructure. We had no waste removal, no basic public health system and it created an environment that was incredibly ripe for disease, particularly the deadly disease of Cholera which had come to London first in 1832 and would basically run through the city in waves every kind of four or five years and 20,000 or 30,000 people would die in the space of three or four months normally over the course of the summer.</p>
            <p>The other thing that happened was it created an environment&#8230; and this is very crucial to the history of London and the history of all urban systems at this particular point in time. It created an environment that was incredibly smelly. Every kind of contemporary account of London during this period talks about the overarching kind of stench that attack you every time you walk through the streets of the city.</p>
            <p>This led to one of the great errors in the history of science and history of medicine, what became known as the &quot;Miasma Theory of Disease.&quot; The belief was that people were being poisoned and particularly, people were contracting Cholera because of this smell, because of something in the air that was causing people to get sick and to die.</p>
            <p>This is Edwin Chadwick, the pioneering kind of public health reformer who is one of the great champions of the Miasma Theory. The quote you saw there before, &quot;All smell is disease,&quot; was from him. That was how kind of extreme the Miasma Theory got. If it was smelly, it was causing you to get sick.</p>
            <p>Of course, we know now that in fact, the theory was dead wrong. However offensive the smell was, they weren&#8217;t actually making anybody sick. What was happening is the water supply had been contaminated. Cholera is a disease you get when the Cholera bacteria infects the water supply and you often get it in places where there are large human settlements where they haven&#8217;t yet figured out how to separate the water supply from the waste systems and that was London in 1854.</p>
            <p>So, the story then really begins&#8230; and I know some of you have read the book and I know some of you know a little bit of the story so I&#8217;m going to tell it relatively quickly and then talk a little bit more about what it means.</p>
            <p>The story really starts in August 28, 1854, when a popular public pump at 40 Broad Street in Soho, London, the most densely populated neighborhood in all of London at that point, a kind of an island of working class poverty in the middle of kind of more posh neighborhoods around it.</p>
            <p>A public watering hole at 40 Broad Street gets contaminated with the bacteria that causes Cholera. And in the morning of August 28th, a little girl living right next door to the pump gets sick and dies shortly thereafter. In the next ten days, the most intense, concentrated outbreak of Cholera sweeps through this neighborhood, literally decimates the neighborhood, right? Ten percent of the neighborhood dies over the course of the next two weeks.</p>
            <p>Far more would have died if the rest of the neighborhood hadn&#8217;t basically emptied out and fled. Some incredibly devastating, incredibly terrifying moment in the history of London, scenes that we really don&#8217;t experience that much more in the developed world, of entire families dying together alone in their little one room flats over the course of 24 hours, just an incredibly tragic and terrifying story in the history of urban life.</p>
            <p>But, what&#8217;s so interesting about this story is that it actually, that devastation and that tragedy ends up leading to a great breakthrough. In a strange way, this is a very optimistic story because of what happens next. And the way that it&#8217;s conventionally told is that a brilliant man, a polymath, one of the great minds of the 19th century, John Snow, hits upon the solution to the riddle of Cholera and figures out that in fact, Cholera is not in the air, is not a product of Miasma, but is in fact the problem of contaminated water supplies and hits upon it by analyzing the deaths in this particular outbreak and he ends up creating a famous map that showcases all the deaths and points a finger conclusively to this contaminated pump.</p>
            <p>Now, to some extent that&#8217;s true, and the way that the story is told, it&#8217;s often told as a story of both a kind of great scientific epiphany and also as a story of great information design. Tufte wrote about it twice in his early influential books on information visualization tools.</p>
            <p>So, we have both kind of science and we have kind of graphic design, mapping, cartography, information design all bound up in the story. Those are important roles, but I think that there&#8217;s something else that we should stress and something else that&#8217;s directly relevant to the kinds of projects we&#8217;re working on today and I was trying to kind of get to when I wrote this book, which is that this is also a story about social systems.</p>
            <p>This is also a story about a neighborhood. This is also a story about amateurs who live in that neighborhood who have a very local&#8230; we might say now &quot;hyper local&quot; kind of expertise about what&#8217;s going on in their communities who were able to share that expertise and share that information and visualize it in new ways and in doing so, they changed the world.</p>
            <p>So, that&#8217;s the angle that I think we need to&#8230; and when we revisit this great, extraordinary moment in the history of London, we need to approach it from that angle and that&#8217;s what I really want to talk about today.</p>
            <p>So, Snow was, in his own way, he was kind of an amateur. He was a physician, he was a local physician working on the edges of Soho. It&#8217;s crucial that he was a resident of the neighborhood working with the residents of the neighborhood.</p>
            <p>But, he was a classic dabbler, he was a classic kind of 19th century Victorian figure who was just interested in a million things and four or five years before he had gotten interested in Cholera and the problem of Cholera and he started kind of speculating on it.</p>
            <p>Before long, he developed this theory that in fact it was a problem of contaminated water and not Miasma. Some people think that he got the theory out of this particular case. Actually, he had the theory before but he couldn&#8217;t convince anybody of it.</p>
            <p>So, he published a number of articles saying, &quot;Listen, the public health authorities have this totally wrong. This is an issue that we need to solve by dealing with the water system. This is not something that&#8217;s in the air.&quot; Nobody listened to him.</p>
            <p>But, when he got word that there was this terrible outbreak that was devastating his own community, he was one of the few people probably in that community who saw this as an opportunity. He thought that concentrated an outbreak suggested that there was probably a single point source to this epidemic. There was probably a single place where people were getting contaminated water and if he could find that, maybe he could finally make a convincing case for the waterborne theory of Cholera.</p>
            <p>So, he went straight into the heart of the belly of the beast, straight into the heart of this terrible epidemic. As the rest of the neighborhood was evacuating, Snow went in and started knocking on doors and started asking people where had they gotten their water. Over time, within a couple of days in fact, all the evidence started to point to this pump outside 40 Broad Street.</p>
            <p>So, in the days and weeks after, he started to try and figure out how he was going to represent all these information that he&#8217;d gathered. So, in the end, he built a couple of maps. This is pretty much the last version and the most famous one.</p>
            <p>There are a couple of things that are exceptional about this map. The basic idea here is each bar represents a death, right? So, this is the pump here at 40 Broad and you can see the concentration of death around the pump and you can see how it fades, it gets less severe as you get further and further away from the pump.</p>
            <p>So, instantly right there, you get the sense that there&#8217;s something fundamentally wrong here with this area. There&#8217; something contaminated. Now, what&#8217;s interesting about this is people tend to focus on that particular part of the information design, the idea of having these black bars represent death so that you can see the pattern being formed.</p>
            <p>But, in fact, that was not actually the most original and not in fact the most convincing part of the map because people had done this kind of map before in a couple of occasions. This is really the most famous version of this kind of design. But, the thing that he did that was really clever and it was much more convincing is this line that goes around the edge of the map.</p>
            <p>This line is basically an attempt to represent time geographically here. This, the space enclosed inside this kind of wavering line is the space of residences that were closer, that were faster, to walk to this pump than it was to walk to any other pump in the surrounding communities.</p>
            <p>So, given that kind of crooked streets and the kind of foot traffic in getting there, if you lived inside this border, you were more likely to go here for your water than you were to go anywhere else. What you see is every space inside that area, even over here in this kind of unusual space, there&#8217;s an intense concentration of death.</p>
            <p>This is not what you would expect if there were some kind of miasmatic force emanating in the air from this particular spot. So, if this was just a particularly smelly pump for instance, if there was just a poisonous stench coming out of this pump, you would see this concentration here, but you wouldn&#8217;t see this concentration here.</p>
            <p>So, those two elements. Actually, Tufte doesn&#8217;t even mention this line in his treatment of the map, which was pretty interesting that he missed that. So, he builds this map&#8230; And this is a great moment in the history of information design, there&#8217;s no question about it. But, there are other elements too that I think are just as important.</p>
            <p>One of them is that Snow had a crucial collaborator who&#8217;s been almost entirely ignored in almost every account of the outbreak and that&#8217;s the Reverend Henry Whitehead who was at the time a 25 or 26 year old kind of local vicar. This is him much later in life, I hope, with the good-looking beard.</p>
            <p>Whiteheads was one these, he was just a classic networker, he knew everyone in the neighborhood. He was the local vicar who would come over and have tea with you, this local vicar who would hang out in the pub. He was just a classic kind of connector figure. He got involved in this case because he heard word that Snow had basically fingered the pump as the culprit in this outbreak and he said, &quot;Well, listen, I know this neighborhood, I know all the people in this neighborhood and I know that&#8217;s the best water in Soho.&quot;</p>
            <p>It had this reputation as being the finest water around town in part because apparently it had a slight carbonated kind of fizz to it, which apparently was a sign that there was some extra decaying organic matter in the water. A little less appetizing if you know that, but people liked it because it had this little kind of soda water-like sparkle to it.</p>
            <p>So, people would go to this pump from quite far away. So, Whitehead said, &quot;I&#8217;m pretty sure that I can disprove this theory just by going around and talking to the people that I know.&quot; Well, what Whitehead had was an unusual access to people and the ability to go in and sit down and talk to people at length because he knew them better than Snow did.</p>
            <p>What often happened was the parents would say, &quot;Well, no, no, we don&#8217;t drink out of that pump&quot; and then after a long period of conversation it would turn out that the eight year old had gone and gotten water from that pump that morning and the parents had known about it.</p>
            <p>So, the more and more people that Whitehead talked to, the more he found there was always some thread connecting back to this pump. The other thing Whitehead was able to do is track down the people who had left. Because he had this kind of thick social network in the neighborhood, he was able to find all these people who had actually left that Snow was not able to get in contact with.</p>
            <p>So, Whitehead ended up being crucial to the investigation. In fact, he was the one who ended up finding kind of the &quot;patient zero,&quot; this baby who had gotten sick on August 28th right across from the pump. Snow did not find this child and in fact, in the kind of ultimate argument that was made for the waterborne theory built around this particular case and built around the map, the existence of this patient zero was what led the authorities to go and dig up the connection between basically the pool at the bottom of his house and the pump and find that there was decaying brickwork connecting the two.</p>
            <p>So, the real kind of lynchpin in the argument did not come from Snow. It came from Henry Whitehead who had no expertise. He wasn&#8217;t even a man of science in any way. What he was, was a local. He was an amateur on the ground in his community who knew his community, who had a certain kind of local knowledge that he was able to share and with Snow&#8217;s expertise, with Snow&#8217;s information design, was able to turn it into something that literally changed the world.</p>
            <p>The other thing that&#8217;s crucial in our context today (that I think has been ignored in the telling of the story) is that they had access to open data archives that had been created by William Farr in the preceding decade. What Farr decided to do was he figured it&#8217;d be very useful to not just report mortality data for the city. That had been going on for a long time, people saying, &quot;OK, X number of people died this week, X number of people died in these neighborhoods.&quot;</p>
            <p>But, he started asking for much more precise information, like the exact location where they died and the cause of the disease and a couple of other things that he added and he would release this information every two weeks. So, suddenly, there was this, in a sense, kind of open-source data that was out there that people could get to that had a standardized kind of format so people could say, OK, I&#8217;m looking for deaths of cholera by neighborhood. And they could get that information once every two weeks. It was incredibly hard to get that, basically impossible to get that without just walking around the city talking to people, talking to individual physicians on your own.</p>
            <p>Suddenly, the city was producing that as a standard bit of information with the premise that if they released it into the wild, other people would do interesting things with it. They would take that data and figure out kind of new things to build on top of that data, new interpretations, and that&#8217;s precisely what Snow and White had did. So, they supplemented their kind of shoeleather detective work, their knocking on doors, with this public data that had become available in the last 10 years. And they built this map out of it. In a sense, it&#8217;s the first mashup, right?</p>
            <p>So, and the other thing, conceptually, here, that&#8217;s really important is this idea of the long zoom, of being able to connect different scales of experience and build kind of causal explanations about the links that unite them, right? So, Snow approached the problem, he actually was very interested in trying to identify this bacteria. He looked with his microscope, you know, trying to see the actual organism that he was kind of in search of, but the technology of the day made it very hard to see things that small. But, he was thinking on the scale of microorganisms.</p>
            <p>He was also thinking on the scale of individual lives, just as Whitehead was. They were thinking on the scale of social networks. They were thinking on the scale of entire neighborhoods. In fact, Snow eventually also built these elaborate maps of the entire kind of public water system in London, which are, in some ways, even more important maps because they showed the broader patterns of water distribution in London. So, he was thinking on this kind of macro, urban scale as well.</p>
            <p>So, the ability to kind of zoom in and out between all of these different levels and to build this kind of bird&#8217;s-eye view of all this behavior and all these decisions and all these kind of patterns of lives and deaths, to learn from it, that&#8217;s an incredible intellectual skill, that ability that can move across scales and across disciplines and synthesize all of that.</p>
            <p>I mean, this is, you know, in a sense, a kind of a social network of dead people, right? They&#8217;re united&#8230; No, I don&#8217;t mean that kind of lightly, I mean, they&#8217;re united by, you know, two shared interests, right? A shared kind of community, they&#8217;re geographically connected to each other, and by a shared interest in the Broad Street pump.</p>
            <p>And by looking at, and kind of building out the model of that network, and by representing it in a novel way, Snow and Whitehead were able to crack this case and eventually convincingly turn the tide towards the waterborne theory of cholera.</p>
            <p>And it&#8217;s important to note that cholera came back to London in a serious outbreak form about 10 years later, and by that point the public health authorities had officially kind of endorsed the waterborne theory and they treated it as a problem of contaminated water supplies. They had already started building the sewers, one of the great engineering achievements of the 19th century, underground, so people don&#8217;t celebrate it as much as they should, to deal, precisely, with this problem. And after that epidemic, in 1866, that was the last time that cholera came to London. It has not been back since.</p>
            <p>So, this was a case where this social network, this group of people, this information design, this map, this open data standard, came together and literally changed the world. And every other city around the world has slowly been adopting these principles of kind of public health organization, of waste removal, of dealing with clean water supplies, because of this map and because of the men and the intelligence that went into this, went into this map.</p>
            <p>I was thinking today that I should&#8217;ve called the book &quot;The Wisdom of Dead Crowds,&quot; right? [laughs]</p>
            <p>These are all these people who, in a sense, died in this incredibly tragic way, but somehow, by looking at the pattern of their deaths, they were able to change the world for the better, right?</p>
            <p>So, this is the legacy that I think we have to think about today, and we&#8217;re at a fantastic kind of turning point in the evolution of this technology and of our opportunities to deal with all these things. So, I want to walk through a few kind of basic points about the geographic web because this is a really exciting time, I think.</p>
            <p>In some ways, it reminds me a bit of the early days of the web. When we think back to all the things that happened, all the innovation that happened, just the tremendous kind of breakthrough of new ideas and new possibilities that happened when the web came along, one of the fundamental questions I think we have to ask ourselves is, why did it happen? Right? Why did we have so much innovation in such a short amount of time? What was it that made the explosion of interest in the web possible?</p>
            <p>And I think, one of the things that you have to say about it that maybe isn&#8217;t said enough is that we had a standardized format for the location of pages, right? We had these URLs that you could point to, and you could reliably say, this page exists here, and if you build another page that links to that page, pretty much you can be confident that you can go from one page to the other.</p>
            <p>And so much comes out of, obviously Google and PageRank, comes out of the ability to have these standardized addresses for information. You can build things on top of, you can built stacks on top of that information because you know where the information is and you have a standardized way of kind of addressing it.</p>
            <p>And I think, the fundamental idea that is so exciting about the geographic web now and all the things that are happening is that we are now starting to get standardized geographic addresses for information online. And when you start to agree upon a set of formats for the real-world location of pages, the content of the page is talking about something in physical geographic space, that&#8217;s going to open up, is already opening up, a series of amazing possibilities that we&#8217;re all just kind of starting to explore.</p>
            <p>So, this is the great opportunity we have in front of us right now, and I think it&#8217;s going to be as important and as revolutionary, not just in terms of virtual space, but in terms of real-world space. What we&#8217;re starting to build is, in a sense, interfaces for urban spaces and rural spaces and suburban spaces, information layered over the actual world. So, it&#8217;s very exciting.</p>
            <p>And what we have, in a sense, are three elements that were crucial to the story of cholera in 1854. We&#8217;ve got local expertise on the ground, we&#8217;ve got people, local bloggers writing about their communities, writing about their neighborhoods, writing about what&#8217;s going on around the corner, the Henry Whiteheads and John Snows of today.</p>
            <p>And what&#8217;s fabulous about these people is that they truly know their communities better than the so-called experts. And when we think about the debate about bloggers and journalism, say, for instance, has been going on for the last five or six years, so much of that debate has been focused on the political sphere, in part because political blogs were one of the first parts of the blogosphere that got attention, and they really got some kind of critical mass.</p>
            <p>And so, we&#8217;ve had endless debates of, you know, should bloggers have journalistic credentials, what makes them different from the experts who write for the op-ed pages and pontificate on television, all that kind of stuff.</p>
            <p>But, all of those questions, wherever you stand on that debate, all of those questions kind of die off when you get down to the level of neighborhoods and communities, the hyperlocal level, because when you&#8217;re trying to figure out what&#8217;s going on at the science program at your kid&#8217;s school that he&#8217;s entering next year, you don&#8217;t want to go to the education beat reporter for the local city paper to find out about it, you want to go to the parents whose kids were in the program last year.</p>
            <p>Those are the true experts. And every neighborhood is filled with people who have that kind of expertise. It&#8217;s just that most of that knowledge and information, in a sense, was trapped in their minds and in their word of mouthe .NETworks.</p>
            <p>And what started to happen with the local blogisphere, with Placebloggers, is that those people now have a megaphone. Those people now have a voice and they&#8217;re able to talk to their wider community in a new way with these new tools.</p>
            <p>But, what is also exciting is now because of open information standards about how we geographically tag that information, and open standards about how we can map that. And the tools from Yahoo and Google and other places that let people map things without having to buy incredibly expensive choreographic software, or do it themselves, there&#8217;s this opportunity now for that local expertise to circulate through people&#8217;s neighborhoods in entirely new ways. We can really invent a whole new way of letting neighborhoods talk to each other and share the knowledge that they have.</p>
            <p>And we have these new ways of visualizing, new ways of thinking about all that data, new ways of mapping it. All of that is right there at our fingertips. It&#8217;s an incredibly exciting time.</p>
            <p>I want to talk a little bit about how we&#8217;ve taken these ideas and animated them at <a href="http://outside.in/" >Outside.in</a>, which is the company that I started right as I was finishing Ghost Map. It was just this process where I was writing the book, I would wake up in the morning and go sit down to work and I would go and look around the Web.</p>
            <p>And what I found myself doing compulsively again and again is going to the local bloggers in my neighborhood. Going to these Brooklyn bloggers. It turns out actually that Brooklyn, where I live, is the leading capital of local bloggers, as far as we know, in the world.</p>
            <p>We did a survey, at least in the United States, of the bloggiest neighborhoods in the country, which we did mostly because we think bloggiest is a word that people should use more. And it turned out, of the top 10 neighborhoods, four of them were in Brooklyn.</p>
            <p>It&#8217;s a very dense community, there&#8217;s a lot of change happening; gentrification tends to cause people to blog more and there are a lot of writers with too much time on their hands in the community as well. All of that kind of was the perfect storm for bloggers.</p>
            <p>As I was finishing the book I was thinking, &quot;Gosh, there are all these people who remind me of Whitehead and there is all this interesting stuff happening. But, there&#8217;s no place to go where you can actually say, I want to see everything that&#8217;s been said in traditional news or through the blogisphere about schools within one mile of my house.&quot;</p>
            <p>That&#8217;s a very intuitive kind of query that you should be able to do. You should be able to say, &quot;I want to filter this by proximity to me.&quot; But, it&#8217;s one of these things that Google can&#8217;t do. Google can show you dry cleaners near your house, but it can&#8217;t tell you what people are actually saying within 10 blocks of your house, or five blocks of your house.</p>
            <p>And yet that&#8217;s the way we organize the world, right? We organize the world spatially. Things that are closer to us mean more than things that are further away. And in a sense, there was this imbalance here where we had all these amazing tools that we except, that we take for granted. And yet something that was so important and intuitive and essential to the way that you organize your life and think about your life what something the technology wouldn&#8217;t do.</p>
            <p>And so, we decided to create <a href="http://outside.in/" >Outside.in</a>, which basically is mapping all of these conversations that are happening in blogs and newspapers, and tagging each little bit of information with as precise geographic data as we can. We have pages dedicated to specific places, to schools, to parks, to restaurants, to dangerous intersections.</p>
            <p>We found everything that we could find from the blogisphere and from new sources and we mapped it to those pages. We mapped also topic pages, so you can find out everything about&#8230; if somebody gets murdered in your neighborhood there&#8217;s a topic page for that person. There&#8217;s also neighborhood pages and topic pages for each neighborhood.</p>
            <p>It&#8217;s this huge array of pages, all of it organized out of this information that&#8217;s circulating around from local blogs and news sources. We are doing more and more and we&#8217;ve been doing it for about two years now.</p>
            <p>One of the things that we are really intrigued with is getting tools to make this easier and easier for people who are creating this kind of content, both for publishers and for bloggers. So, the people who want to make the kinds of maps that Snow made, how can we make it easier for them to do that and to organize their content without having to think about GRSS, or latitude and longitude and things like that?</p>
            <p>This is something I haven&#8217;t shown before; these are some early designs for this product, Geo Toolkit, which we have in Alpha right now. Basically, this is a tool that lets anybody who publishes something and has a feed of any kind, go in and make sure that their content is being geo-tagged properly, it&#8217;s kind of a geo SEO, you can think about it that way.</p>
            <p>And then it basically gives you geo analytics for how your content is existing in the world. So, this is an example of a map, this shows you the places that you&#8217;ve written about. But, it doesn&#8217;t just show you the places as little pushpins on the map. Because what we want to do is show you, in a sense, the social networks of conversation around the places you&#8217;ve written about, and how much you are dominating that conversation.</p>
            <p>So, these are all the places that you&#8217;ve written about. The overall size of this little pie shows the overall volume of conversation about that place. And the division between the orange and the blue shows you the orange is your stuff, the blue is everybody else&#8217;s stuff.</p>
            <p>You can quickly see, you&#8217;ve written three stories about East River State Park, and total stories, there are 20 out there. And then, you can just click on the Place Page name and you&#8217;ll see all the stories that have been written. You&#8217;ll see that community that&#8217;s been build around that particular place. So, in a sense, you can see your mind share of a given place in your world.</p>
            <p>We are building these things that have stats that show you&#8230; We are going to be able to set it up so you have rankings within your neighborhood, so that you can say proudly that you are the number three crime blogger in Park Slope. Hopefully, that will set off a lot of competition between people.</p>
            <p>But also we are analyzing all the feeds that are coming in and we are looking for place names. We are looking for neighborhood names, we are looking for places and we are automatically geo tagging for people. We&#8217;ve built an algorism that&#8217;s getting smarter and smarter at detecting these places and automatically adding that machine-readable geo stamps to those pieces of data.</p>
            <p>Now, you can correct it, you can fix it, you can make it smarter by contributing to it. It&#8217;s a tool that lets you actually see the geo tags that have been attached and to maybe refine them if you want. So, all that stuff is built into Geo Toolkit.</p>
            <p>At the same time, we want to make it easier for people who aren&#8217;t necessarily bloggers, who aren&#8217;t necessarily actually feeding information into the system, to see all this and come up with new ways to visualize this.</p>
            <p>This is the product that we launched this summer, which we are really proud of, which is Radar. And what Radar is trying to do is to do this idea of the long zoom. What Radar shows you is, you give Radar your exact address and it will show you what&#8217;s happening within a thousand feet of you. And then, there is another layer of zoom and it will show what&#8217;s happening in the neighborhood you are currently in. And there is another layer of zoom and it will show you what&#8217;s happening in the city.</p>
            <p>And then, you can track specific places that you are interested in, even if they&#8217;re in other cities. You can say, &quot;OK I&#8217;m really interested in this development in Manhattan, even though I live in Brooklyn. Or, I&#8217;m really interested in this hotel that&#8217;s opening in San Francisco; and so, anything that comes up about that place will show up on your Radar as well.</p>
            <p>What we are trying to do here is to enable people to actually see what&#8217;s happening in their world, particularly that thousand foot view. Because that thousand foot view is the scale of true meaning. Anything that happens within a thousand feet of your house or where you are standing is almost enviably going to be interesting to you because it&#8217;s so close.</p>
            <p>One of the things that we are starting to do is actually parse twitters, as well. We are just watching the twitter stream and, when we see people mention neighborhoods, we will pull them out. Then, we will do automatic place detection based on those neighborhoods.</p>
            <p>In this case, somebody has mentioned that they are looking for a nice Park Slope restaurant, and they mention Blue Ribbon, which is a restaurant on Park Slope. We have taken that, and anybody who lives within 1000 feet of Blue Ribbon is going to see that in their Radar. And anybody who has let us know that they are standing within 1000 feet of Blue Ribbon is going to see that in their Radar. They are going to see that in the neighborhood &quot;Park Slope&quot; view of Radar.</p>
            <p>It is this ability to send a message out to the community around a specific place in an entirely distributed way, without having to think about your location at all.</p>
            <p>What is important here is that the geographic information is not where the twitterer is; it is not where Sammy Sanchez is when he sends his twitter. The geographic information that is relevant here is Blue Ribbon. Right? Or Park Slope.</p>
            <p>They could be twittering this from Manhattan or from San Francisco, and the GPS coordinates of the twitterer is not going to be relevant here. What you have to be able to do is understand that Blue Ribbon is a restaurant in Park Slope, and that is the relevant geographic frame for it.</p>
            <p>So, that is what we are trying to do.</p>
            <p>Now, the other thing that I think is crucial, and maybe, I can say this&#8230; It is not that it is disappointing, but I think that there is more to do. We have this great opportunity. But, if you look at the vast majority of the start ups and privately funded companies that are trying to explore the possibilities of the GeoWeb, there is this hugely disproportionate emphasis on finding restaurants, and finding local businesses. Right?</p>
            <p>In fact, the kinds of queries that I was talking about, &quot;Show me what&#8217;s happening within one mile of my house.&quot; That&#8217;s the kind of stuff that Google does well. You can see all of the restaurants within one mile of your house.</p>
            <p>There are a lot of great services. Yelp is a fantastic site, and is doing really innovative things. But, there has been this heavily strong emphasis on reviewing and finding local businesses: finding a dry cleaner or finding an Indian food place. I think that while this is immensely valuable, if you think about your life&#8230; If you think about all of the things that have a geographic frame to it in your community and your neighborhood, all of the events that happen to you that are meaningful in a geographic way, that the percentage of those which are about finding a restaurant or a dry cleaner, I would say, would be vanishingly small.</p>
            <p>There are a huge number of other things that happen in our world that are grounded in location. I think that we are spending too much time focusing on this one small slice of the problem, and not enough on this big open space that has not yet been fully explored.</p>
            <p>Our philosophy at <a href="http://outside.in/" >Outside.in</a> has been to, certainly, let people blog about a restaurant and have it show up on <a href="http://outside.in/" >Outside.in</a>, and then ask somebody about restaurant recommendations and that twitter. But, we are trying to do more than that as well, and to have it be whatever anybody is interested in.</p>
            <p>If there is a cholera outbreak in your neighborhood, you will hopefully be able to use <a href="http://outside.in/" >Outside.in</a>. Hopefully, it won&#8217;t happen to you, but you never know.</p>
            <p>I will give you just one example of this. And that is, we set up Radar so that you could get email alerts if there is anything within 1000 feet of you which comes over the transom.</p>
            <p>And, so, my family and I left the city for about six weeks, and we were out on the eastern end of Long Island. I had left my Radar location back at home, and I was getting these daily alerts of things that were happening within 1000 feet of my house. It was a little bit like having a security camera installed in your neighborhood, right around your house. It was just a kind of daily buzz of things that were happening&#8230; a place was opening or closing or somebody got mugged or a house got sold. All of the kind of buzz that you would get when you are home and talking to people, I was able to get remotely.</p>
            <p>One day, in the middle of the summer, I got this in my mail. It said, &quot;This item just popped in your <a href="http://outside.in/" >Outside.in</a> Radar. Van on fire in front of Dizzy&#8217;s.&quot; Dizzy&#8217;s is a restaurant, which is a block from my house. OK, that sounded a little disturbing. In about two minutes I had this&#8230; In fact, another description said that a van had exploded a block from my house, which sounded even more startling. This is the kind of thing where it was fine. It was not really a threat. But, there is a giant flaming van within a block from my house. I would kind of like to know about it. What I think is striking about this is the chain that got this picture to me.</p>
            <p>The chain was&#8230; Somebody on a message board posts something that says there is a van on fire outside of Dizzy&#8217;s. They don&#8217;t think about geotags, they don&#8217;t think about GRSS, they don&#8217;t think about lat-longs, they don&#8217;t think about any of that stuff. They are not using GeoToolkit, they are not using us. They just say that, and we are watching that feed. We pick up Dizzy&#8217;s. We tag it with the exact location of Dizzy&#8217;s, and then we update everybody&#8217;s Radar, Dizzy&#8217;s page and the Park Slope page with that information. Then, anybody who subscribes to an email alert gets that stuff pushed out to them.</p>
            <p>There I have a picture of this van in such a short amount of time. This is exactly the kind of story that is relevant to me on a 1000 foot scale. But, unless this van turns out to be some kind of terrorist plot or sets fire to a larger building, it&#8217;s never going to show up in the local newspaper. It will never even be reported, likely. Right?</p>
            <p>But, it is relevant, because I am so close to it. It requires this social web of people on the ground in these neighborhoods who are writing about these things. And it requires tools to grab that information, aggregate it and makes sense of it&#8230; share it and amplify it.</p>
            <p>The opportunity of doing that, of creating new ways for that information to circulate, needs physical spaces to connect people. It needs to not use the web as a mechanism to escape the real world, but instead to use the web as a way of enhancing the real world, to make people feel more connected to your community, even if you are 200 miles away from it. That is the great opportunity for it.</p>
            <p>I always think about this line that I wrote about in my second book, &quot;Emergence,&quot; from Jane Jacobs. She was one of the great urban theorists and an inspiration for me. In her book, &quot;Death and Life of Great American Cities,&quot; she talks about the power of great, largely pedestrian-based cities and how their, often surprising, safety comes from the number of eyes on the street &ndash; the number of people who are members of the community who are out there every day, just looking at things.</p>
            <p>She was writing about it in the context of safety, that the streets which are busy tend to be safer. You do not need police, you just need to have people walking around and keeping an eye on things to make cities feel safe. It is the deserted cities &ndash; cities where no one is out &ndash; and it is back allies where no one is watching&#8230; That is where crime tends to happen.</p>
            <p>I think, about those eyes on the street in the context of the GeoWeb. What is fascinating about this opportunity is that the people who are sitting there looking at that van on fire, the people who are sitting and looking at the new restaurant that is opening up, the people who are sitting there looking at a new brownstone that has just sold&#8230; Or talking about crimes that have happened or talking about what is going on in their public school&#8230; Those eyes and the intelligence behind those eyes are what make neighborhoods great.</p>
            <p>For the first time in the history of recent technology, we have an opportunity to take new technology and make that intelligence more connected, more grounded and to make that vision clearer.</p>
            <p>Thank you, very much.</p>
            </blockquote>
            
		  <p class="transcript_credit">Transcription by <a href="http://castingwords.com">CastingWords</a>, sponsored by <a href="http://www.opera.com">Opera</a>.</p>
	</div>

</div>


<?php include("../includes/footer.inc.php"); ?>