<?php 
	$title = "Daniel Burka";
	$section = "schedule";
	include("../includes/header.inc.php"); 
?>

<div class="container clear">
	<div class="secondary">
		<ul class="speakers">
			<li><a href="/schedule/StevenJohnson.php" class="speak2">Steven Johnson</a></li>
			<li><a href="/schedule/AleksKrotoski.php" class="speak3">Aleks Krotoski</a></li>
			<li><h2><a href="/schedule/DanielBurka.php" class="speak4">Daniel Burka</a></h2></li>
			<li><a href="/schedule/MattJones.php" class="speak5">Matt Jones</a></li>
			<li><a href="/schedule/MattBiddulph.php" class="speak6">Matt Biddulph</a></li>
			<li><a href="/schedule/JoshuaPorter.php" class="speak7">Joshua Porter</a></li>
			<li><a href="/schedule/JeremyKeith.php" class="speak8">Jeremy Keith</a></li>
			<li><a href="/schedule/TantekCelik.php" class="speak9">Tantek Celik</a></li>
		</ul>
	</div>
	<div class="primary transcript">
	<h2>Designing for Interaction</h2>
		<p class="transcript_credit"><a href="http://opera.com"><img src="/img/sponsors/opera.gif" alt="Opera Software" /></a>
		Transcription sponsored by <a href="http://www.opera.com/">Opera</a>.</p>
		
  <blockquote> 
            <p> I took this picture back in November of 2005. At the time this was in the very, very early days of Digg. At the time I was living in Toronto and coming down to San Francisco about once a month to work with Kevin and the small team at the time that was building Digg.</p>
            <p>I remember I came down and one of the early investors in Digg had some really nice seats at the ballpark in San Francisco; the AT&amp;T park. Kevin and I went down there. Earlier in the day we had been working on new Digg features and then we went to the ballpark later in the day.</p>
            <p>I can actually remember sitting there in the crowd. This was the last game of the season. The Giants hadn&#8217;t done that well, but there was a huge crowd that showed up to see their last game.</p>
            <p>I was sitting there and I was looking out over the crowd, and I was thinking &quot;That is a lot of fucking people. That is a big crowd.&quot;</p>
            <p>Because of course the ballpark in San Francisco, being San Francisco, has wireless Internet, we looked up how big the park was on Wikipedia. It seats 41,500 people.</p>
            <p>Just earlier in the day Kevin and I had been talking about the upcoming section of Digg and how much participation there was there. There was more than that number of people already participating on Digg at that stage of the site.</p>
            <p>I was thinking in the real world, over 40,000 people is huge. That is a massive number of people. That is a huge crowd. When the ballpark has a game, it disrupts that entire part of the city, and they play a couple times a week.</p>
            <p>There are traffic jams all the way up Third Street. Police have to come out and patrol the streets and make sure that opposing fans don&#8217;t get in fights with the San Francisco fans, especially when they are playing the Dodgers.</p>
            <p>There is this whole business around it. There are places that do parking just specifically for game day. There are places that sell souvenirs that are only open on game day. There are pubs and bars that cater specifically towards the baseball fans who come out to the stadium, let alone the infrastructure just for the stadium itself, which is this gorgeous, huge structure right on the water.</p>
            <p>If you are ever in San Francisco you should really go to a game. It is a beautiful experience. I was thinking that is a lot like what we are doing. We are building this infrastructure. We are building this whole system and there are other people on the side, like those vendors, who are building into your <abbr>API</abbr>s; that kind of thing.</p>
            <p>What you are doing is building this whole infrastructure to allow these people to interact with each other socially around something.</p>
            <p>People don&#8217;t come to the baseball game just to watch the baseball. They are coming to interact with all of the other fans. They are there to heckle the other squad, right? This is a lot like what we are doing with something like Digg.</p>
            <p>So I am going to talk a little bit today about what we do at that kind of scale of social interaction that allows people to have good connections with each other.</p>
            <p>I was looking through the points I wanted to make and they kind of fall into three categories of issues that I have found we have been focusing in the last year or so on both Digg and on Pownce as well.</p>
            <p>You see they are kind of general trends or challenges that a lot of social sites are facing. The first challenge is getting people to sign up for your site, so increasing the level of participation.</p>
            <p>The second challenge is once those people are already participating on the site, how do you encourage them to do positive behaviors instead of negative behaviors or just solo things? You want them to be social on your site.</p>
            <p>And then the third thing, particularly from a design perspective, is how do you build a user interface that works for a very, very heterogeneous community? So there are lots of different types of people on your website and they have different levels of experience. They have different interests. They have different things that they think are important. You want to build an interface that can adapt to all those things.</p>
            <p>So the first thing that I am going to talk about is how do we encourage people to participate? This is particularly important on something like Digg, which is all about the people. The more people we have participating on the site the better the idea we have of what is actually popular on the Internet.</p>
            <p>One of the issues we have, not to take the baseball metaphor terribly too far, we have a lot of people who watch on television at home. We have something like three million registered users on Digg, but every month we have 30 million people who visit the site.</p>
            <p>So that is a huge number of participants, but at the same time there is this even greater pool of people who are watching it from home. They are not actually participating. Our baseball team can&#8217;t hear them cheering. So we want to actually figure out ways that we can involve them in the site.</p>
            <p>One of the ways that we are looking at doing this is to increase the benefit for people. The way we do it currently is we use phrases like &quot;Discover the best of the web.&quot; We say things like &quot;Promote stuff that is important to you.&quot;</p>
            <p>Those things are very altruistic. It is saying &quot;Hey, you are part of a community. Do stuff that is nice for the community.&quot; That goes so far. There are certain people who think that way. They are like &quot;I really believe in this thing. I really want to support it. I want to be part of what is going on here.&quot;</p>
            <p>You can really tap into people if you can tap into their self interests and you can say &quot;If you do X you will get Y.&quot; If Y is tangible enough for them, we can get them to participate more.</p>
            <p>So this is something, kind of a philosophy that we are taking towards building new features. One of the first steps that we have taken recently in this regard is something we call the recommendation engine on Digg, which is currently in the upcoming section; so stories that haven&#8217;t been promoted to the home page yet.</p>
            <p>So the basic idea of this feature is it is taking your activity on the website; so you are digging, and soon it will also be you are burying your favorites; this kind of thing.</p>
            <p>It is looking at that and it is finding other people who do similar activities to you, and then it is looking at what those similar people do and saying &quot;Hey, you might want to check out the stuff they do because they are similar to you.&quot;</p>
            <p>The great thing with this is the more you tell our system, the better the system can be at delivering content to you. So in the upcoming section of the site we get something like 16,000 submissions at a time sitting in that pool.</p>
            <p>The upcoming section cycles. A story only sits in there for like 24 hours. To take that 16,000 and boil it down to the 15 or 30 stories that you will really be into is quite a challenge. The more you tell us the better we can do about it.</p>
            <p>So that is a nice, genuine, self interested benefit to the user because we can say on the right&#8230;You will see I actually participate in the website a lot, but up here on the right it says &quot;You are doing great. Keep digging.&quot;</p>
            <p>But if I had dug less items, if I only had three things here, it will tell me &quot;Go dig another 15 items and we will be able to increase the accuracy of these recommendations significantly.</p>
            <p>So we are encouraging people to participate in the site, the people are getting better stuff, and so they will participate in the site even more. That cycles really well. It also recommends people to you, so it is encouraging you to friend up people who happen to be similar to you. After we implemented this feature we saw a significant increase in the amount of participation in the upcoming section, which is really valuable to us because it lets us have better vetted stories reaching the home page.</p>
            <p>And it also saw a significant increase in the number of friends being added because people were discovering people they didn&#8217;t really know but they shared interest. So they are discovering new people, which is a great feature.</p>
            <p>Another thing that we are trying to do to increase the level of participation on the site is reducing the barrier to entry, so making it easier to register on the site and get going. We are doing this in two ways.</p>
            <p>One, we are going to be implementing this feature that basically when you dig something, you are going to get a small dialogue box that lets you register right there. Currently the site brings up a silly little message that tells you, you can&#8217;t do that. You actually need to join or register.</p>
            <p>The incentive to keep going, you are not sure what registration means or how many fields it is. This significantly reduces that. But the even more important thing here is we are working with Facebook on implementing Facebook Connect, and we are also going to implementing OpenID at the same time.</p>
            <p>So if you have got a Facebook account and you have never registered on Digg before, you will be able to click the Facebook link. If you are logged into Facebook you will automatically have the opportunity to import all of your friends. You can skip almost all of the registration steps. You don&#8217;t have to tell us your name, your location, or any of that stuff because we can import it directly from Facebook.</p>
            <p>You can choose which stuff to show, which stuff not to show and you are in. So the big thing we can avoid there too is the email confirmation step, which is a huge pain in the ass for us, and we lose a lot of people on that stage or registration. So this will be a big benefit to us.</p>
            <p>The other thing that we might be doing in the future, and I have talked a lot about this recently, and this ties into some of the stuff that Josh Porter was talking about earlier today, is allowing people to dip their toe in the water before they really get going.</p>
            <p>Currently on the site you can&#8217;t do any of the active stuff until you actually register an account. But you are not sure why you should register an account until you have done some of the active stuff and see the benefits, right?</p>
            <p>So we want people to be able to get going quickly and get invested quickly. For an example for a site that does this extremely well is Genie, which is a genealogy website. I think this is probably the best home page of a Web 2.0 website. It is totally brilliant.</p>
            <p>They do a few things here. I think we can learn some lessons for this on how we do Digg and possibly Pownce. What they do on one hand is similar to many sites. They tell you what they do. That is fine. They can write a bit of a description about what they are and why you might be interested, what you might use Genie to do, but that only goes so far.</p>
            <p>The other thing that they do, which is awesome, is they show you what it is. You can see that it is a family tree, and if I enter my information there I will be starting a family tree.</p>
            <p>So they not only tell us but they show us, and then the truly brilliant part is they only ask you for three things. They ask you for your name, your email address, and your gender, and then you start a tree. It is super easy, but once you get to the next step you feel like you have actually invested something in that website.</p>
            <p>You get a tangible thing like &quot;I just did that. I started my family tree and I have got the opportunity to either keep filling out my family tree, to email it to one of my relatives, or then to register an account and get the full experience and save it.</p>
            <p>So it is really great that you get this really easy entry. They get your email address right off the front and then they give you that strong incentive to register because you have already done something, now you want to keep it.</p>
            <p>On Digg I think we are definitely going towards the model where I would be able to digg a few stories and even from there I could go to the recommendation engine and it would say &quot;Here is some other content that you might be into because we only need a few stories to be able to start recommending content to you.&quot;</p>
            <p>And then if I am enjoying this and everything is going well, we will have a feature in the UI that says &quot;Do you want to convert this account into a real account and go through the new streamlined registration process?&quot; Hopefully we significantly increase the level of people who are participating.</p>
            <p>So the second challenge is now I have got way more people actually participating on the website, which is great, but how do I encourage them, once they are there, to do positive things?</p>
            <p>I don&#8217;t want them going off and joining the infamous &quot;Barry Brigade&quot; on Digg, which I am not sure really exists, but it something that people fear, and writing negative comments about people, flaming people.</p>
            <p>We want to avoid those kinds of behaviors. Something that is as big as Digg that has so much participation, this is something we struggle with all the time.</p>
            <p>One way which is obvious I guess, and we all do it already, is having personal profiles. So having a profile, and we attach all of your activities to that profile, gives you the sense of trust that you know who the other person is. Any action that happens on the site you know who did it.</p>
            <p>Even if it is not a real person, it is amazing how much even a nick name, once you start recognizing it, you can build up that trust.</p>
            <p>This is an example. This is the Silverorange Internet. This is something I worked on way back in&#8230;This is a screenshot from recently, but this UI was built in 2000.</p>
            <p>I remember this was my first experience designing something that had avatars in it. The immediate emotional reaction to that was so strong. The original UI for this didn&#8217;t have any images with it and was just kind of like emails, right?</p>
            <p>The minute we added those images, suddenly it felt like a conversation. I know this is kind of like anecdotal, but the emotional reaction to that was so strong. It was so positive.</p>
            <p>It is no wonder that Twitter, and Pownce, and Digg, and all these sites now use avatars all the time of course. I think Last FM has a great example of a user profile and it is something I have used as inspiration. So nice work Hannah; wherever you are. Last FM&#8217;s designer is here.</p>
            <p>Something they do really well here, and this is the profile for Andrew Wilkson, a friend of mine from Canada, is they mix up a combination of stuff that the user has said about themselves, as well as stuff that they have done, as well as stuff that Last FM can infer about the person.</p>
            <p>So first of all they have got some information up top that the user has entered about themselves. They have told us what his name is, where he lives. He has entered a link to his Tumbleog, which is cool because I can go learn more about him.</p>
            <p>Now what they have done is they are actually making a connection between me and him. So even if I wasn&#8217;t his friend, it is going to tell me if we have similar musical interests or not, which in a music scenario gives me a sense of trust. Does this person have good musical taste? If he listens to &#8216;N Sync I hope we don&#8217;t line up!</p>
            <p>Then what they also do here is they list stuff he has listened to recently. The really important thing with these last two features is Andrew doesn&#8217;t need to come to Last FM to keep this stuff up to date.</p>
            <p>If I come to his profile today and he happens to be scribbling his activity, it is going to be there right on his profile. So his profile is perfectly up to date. We can&#8217;t expect people to be going to all the social networks you belong to. We can&#8217;t expect you to be going to each of them and updating your profile all the time.</p>
            <p>So I really like&#8230;This is something I have done on Digg quite a bit. This is my user profile on Digg, which as you can see is similar in some ways. There is some information that I have entered, some information that is inferred.</p>
            <p>I like this that I don&#8217;t need to think about my user profile to keep it interesting; to keep it up to date. We do something here where we list your recent activity. I don&#8217;t think my laser is working, but your recent activity in the bottom left as well as your favorites.</p>
            <p>Your favorites are something that you didn&#8217;t explicitly have to do in your profile, but by listing it as a favorite you can kind of pin it to the top of your profile and draw more attention to it at say &quot;This story was actually special to me.&quot;</p>
            <p>I think that is something, if we do an extroversion of the profile pages, we could do a lot better even. Something on Pownce we do in your user profiles, and I think Tantek, who is speaking after me, is going to talk a little bit about this is we let you link to your other profiles very explicitly.</p>
            <p>This is great because why should I have to upload my images, more images of me, to another website when I have already got a Flickr account? Why would I type in which albums I like? This is what you have to do on Facebook for instance. Why would I type in what albums I like when Last FM already knows?</p>
            <p>This works really well. I know I have gone to a few people when they friend me, and I go to look at who they are, I want to go see pictures of them. I click on their Flickr link. I can see a whole bunch of pictures of them in an interface that actually is optimized to look at images. It is great.</p>
            <p>Another way that I have been thinking a lot about on Digg every time we build a new feature, and this is also something I focus on a lot on Pownce, is focusing in on tension points.</p>
            <p>There are very small things. If you know that a piece of your site is a real potential for conflict, just little tweaks of a copy, writing something&#8230;Like during the submission process on Digg, I know people get frustrated that we are going off and we are pulling the other website, spydering for images, and doing dupe detection, that kind of thing.</p>
            <p>But just a little bit of fun copy in there, don&#8217;t be flippant, but just some casual copy like &quot;Oh we are just grabbing that information. Hang on a second while we get it.&quot; Stuff like that can really take out a lot of the potential for animosity, particularly really in potential areas where people interact with each other, like in the submission process.</p>
            <p>There are little pieces in there that indicate you are writing a description for your piece. Think about how other people will be reading this. In the comments we could probably do better about not flaming people or &quot;Look back at your comments to see how many people voted it up and down. See if you are actually writing stuff other people like or if you are being a jerk you will know.&quot;</p>
            <p>I think a site that does this extremely well&#8230;I really like this design. I am not sure who at Satisfaction did this, but this is from Get Satisfaction, which is a fantastic&#8230;How would you describe it? It is kind of a self help website.</p>
            <p>So if you have got a problem with an Apple product you can go on there and other Apple fans will help you fix your Apple product; that kind of thing. We use this for our support on Pownce. It is superb.</p>
            <p>What is going on here is you have often got a really, really negative thing going on. If a person is coming here, there is a good likelihood that the reason they are here is because something is broken and they are not happy with it.</p>
            <p>If we made a coding mistake and their user profile is not working, they will come on here and say &quot;My user profile XYZ is broken. What the hell? You guys should really fix that.&quot;</p>
            <p>But what they have done here is at the bottom they have got these little things. &quot;How does this make you feel?&quot; Well it makes you think &quot;OK. How am I coming across? How do I want to appear to other people when I am communicating this?&quot;</p>
            <p>I am sure all of you guys have experience with relationship-ending <abbr>IM</abbr> or email conversations. People are horrible at communicating online, particularly in a forum like this.</p>
            <p>So some very smart person at Satisfaction had the idea &quot;You should think about how you are feeling and express it explicitly.&quot; I think it is awesome.</p>
            <p>People will write on there and they will use the frowsy one. They will say &quot;I am really, really, really frustrated.&quot; That is cool. I know you are frustrated. It is good to know. Then when I respond, I am like &quot;Oh it was really an easy fix. No problem. I am really sorry you had to deal with that.&quot; I respond with the little guy with the tongue out and they respond like &quot;Oh, thanks a lot!&quot; and they have the little smiley face.</p>
            <p>This is dorky as hell, right? But it really works. I have though about how we can implement more of this stuff into projects we are doing. It is stupid simple. You could implement that in an hour, but the idea itself is so strong.</p>
            <p>The other thing you want to do is avoid negative competition. You definitely don&#8217;t want to make this puppy cry because he is adorable. So this is something we struggled with on Digg for a while.</p>
            <p>We had a top users list. I am not sure if you guys are familiar with it. There was a bit of a scandal on the website about this because what we had done was kind of dumb. We had set up a system that listed the users numerically; who was in the top 100, who was in the top 500, but it was a stupid simple figure. It was &quot;How many stories did you get to the home page ever?&quot;</p>
            <p>The problem with this, I think is probably obvious, is that once you got a head on this game you could really stay out ahead, because if I joined the site tomorrow and there is somebody who has been on it for two years and has 600 home page stories, well that is quite the mountain to climb to catch up to them. It is just about impossible.</p>
            <p>New users are frustrated because they have no chance of getting on this list. The existing users were happy with this because they drew a lot of attention to themselves. But to climb the list they were starting to resort to negative behaviors we weren&#8217;t very happy with like submitting duplicate content and bypassing our duplicate filter, which isn&#8217;t terribly hard to do.</p>
            <p>By doing that they could steal stories from new users and use their friends network to promote that version of the story instead of the original. That is really frustrating.</p>
            <p>But the biggest problem with this is that we designed a system that encouraged that kind of behavior. So at the beginning of the website that was great because all these guys joined at a similar time. For the first year or so this was really a boom to the website. There was a friendly competition to try to get to the top of the list.</p>
            <p>But once the site hit a certain critical mass, this feature became less and less useful and became more and more negative. Eventually we took it away from the site. We should have done it sooner but it was the right decision.</p>
            <p>Josh Porter actually wrote about this. If you are interested in the subject, I think he did a really good analysis of why this feature was good at the beginning, why as it started scaling it became less and less useful, and why we made the decision to get rid of it. I kind of wonder if he had a mic in the office because he gets it awfully accurate.</p>
            <p>The third challenge that we are facing, and this is kind of a general problem&#8230;I shouldn&#8217;t call it a problem. This is a general challenge we have had on social websites for forever I guess: allow for flexible participation.</p>
            <p>So allow for experts. Allow for novices. Allow for people with niche interests. Allow for globalists. Allow for people who post three messages a day and have two friends at the same time as allowing for people who have 5,000 friends like the Robert Scobles of this world.</p>
            <p>I don&#8217;t know if you guys saw that graph earlier, but his Twitter graph is preposterous. Building a website that works across all these users is an ongoing challenge and I think no one&#8217;s really cracked it yet. You know, Pownce is just something we struggle with a lot. You know, making it interesting for people who&#8217;ve only got two friends but still can, you know, maintain the flow without being too fast for, you know, people like Kevin who&#8217;ve got, you know, 16,000 followers.</p>
            <p>So the challenge is to adopt a different data. This is, well, I guess what I was just talking about. So, this is kind of separate issue. But one of the issues on social sites which is, I think is a really fun challenge is that people enter all kinds of shit on your website. So, if you have anywhere where people can enter anything, they&#8217;ll enter just about anything you could imagine. And so, as interface designers we have to adapt for that kind of stuff, and actually use Ben Roethlisberger.</p>
            <p>He is an American football player, a quarterback, and he makes a &#8212; I don&#8217;t know how many of you guys are, you know, kind of graphic designers but if you&#8217;re building, you know, sites, he makes a great example guide. Because he&#8217;s &#8212; his full name is Benjamin Roethlisberger. And so, he&#8217;s got a really, really long last name, and a long first name. But there are lots of pictures of him online and stuff and biographies. So, you know, whenever I am doing user profiles, I often use him as kind of my example guide.</p>
            <p>Because &#8212; I actually was just introduced this word recently, I guess, chemists use a term called unobtainium, which is an element that doesn&#8217;t exist. And so when they are working on experiments, they&#8217;re like oh, I just wish I had unobtainium. You know, I could do such and such. And so, in one scenario unobtainium is, you know, infinitely strong and infinitely light, you know. In the other scenario, it&#8217;s, you know, has, you know, infinitely frictionless or something.</p>
            <p>So, I think as designers we&#8217;re really, really, really tempted to use unobtainium when we are building user interfaces. I know I am guilty of it. You know, I&#8217;ll mock up something and I&#8217;ll make it look just perfect. And, you know, the user entered just the right amount of data, and their pictures all were, you know, perfectly aligned and looked great. But of course most people don&#8217;t do that stuff and aren&#8217;t as inter-attentive as I am and so, what I have gotten more into the habit of doing is doing the Benjamin Roethlisberger.</p>
            <p>Entering, you know, silly data, entering, you know, finding users who, you know, are &#8212; I go to someone&#8217;s MySpace profile for instance and copy their stuff into your new user profile because, you know, they&#8217;ve probably got bad taste and, you know, they wrote one time where you expect a paragraph that kind of thing. And so, it&#8217;s a, you know, much, much more useful to build realistic comps.</p>
            <p>For the flow issue, for dealing with how much content comes through someone&#8217;s stream, I think Facebook is probably doing the best out of anybody. So, you know, something like Twitter, stuff like Pownce were pretty basic about it in terms of, you know, just everything coming through there, you know, FriendFeed deals with the same issues. But Facebook has this thing where they basically have an algorithm that tries to determine what you think is interesting, and what you don&#8217;t think is interesting.</p>
            <p>And they try to feed you the right stuff. It kind of breaks down that you&#8217;re never sure if you send something put like say, and their new UI can send an image or something. But I&#8217;m never sure of all my friends receive that or not. You know, like hey, you know, you talk to your friend Kevin, it&#8217;s like hey, Kevin did you see that image I posted yesterday, and it&#8217;s kind of a crap shoot if he did or he didn&#8217;t, right. And they kind of get around this a bit by having this really nice adjuster for the defaults.</p>
            <p>So, if you always want to catch all of your friends&#8217; images you can, you know, crank that feature up. But, you know, creating something like a preferences pane like this is always a bit of a crutch. It&#8217;s, you know, you aren&#8217;t able to come up with a good enough default thing that people have to able to adjust it. So, I think this is something where, as designers we&#8217;re all going to be struggling with for a few years, until we &#8212; you know, it&#8217;s going to different for every website. But I just think it&#8217;s kind of an open ended challenge.</p>
            <p>Another thing for creating a site that adapts to enough people is the idea of following trails, or following what people actually do. I think Jeremy Keith called it paving the cow paths. So, don&#8217;t be afraid to watch what your users are doing, and then adapt your website to, you know, do your stuff that they &#8212; it turns out they think is really popular.</p>
            <p>So, on Pownce for instance we originally thought that events and messages and files especially, we were pretty certain files was going to be the biggest type of thing people are going to send to each other. It turns out links is easily the biggest thing. And what people were doing was that they were sending videos to each other. So, they&#8217;d send YouTube links. What probably should have been obvious to us when we were building it, but we built a pretty quickly and wanted to get out there for this exact reason.</p>
            <p>We wanted to see how people actually use a system instead of how we assume they&#8217;d use it. So, you know, it became pretty obvious to us that it was going to be really easy just to suck in the videos and show them right on the site. And so, Leah and some friends came up with a standard called oEmbed, instead of, you know, writing separate code for every video site, they came up with a nice standard.</p>
            <p>Now a whole bunch of websites like Flickr and Vimeo and a ton of websites even Hulu which is this great American television site have implemented it so we can, you know, import the videos into the site. So, that was, you know, a lesson we got from our users, hey, you really want to do this thing, OK, we&#8217;ll enable you to.</p>
            <p>On Digg that&#8217;s been, you know, a huge inspiration for us for adapting the comment system. This is something I could, you know, do a two hour lecture on, you know, how the comment system evolved to what it is today. But there were huge parts of this like; we originally implemented threading because we saw people saying at so and so higher up in the comment. This was, you know, years ago when Digg was still quite small. And so we said, oh, OK, you know, the site&#8217;s big enough to warrant threading.</p>
            <p>And that&#8217;s kind of an interesting lesson because I was looking at Pownce, which has much smaller conversations because they&#8217;re not about &#8212; they don&#8217;t &#8212; we don&#8217;t have like the mob aspect of Digg Everything&#8217;s more about you and your friends, and you don&#8217;t see them doing that.</p>
            <p>We actually had a good discussion with a bunch of, you know, our &#8212; you know, some of the biggest users of the site the other day, whether or not we should implement threaded comments on Pownce, and, you know, we all came to the conclusion that we shouldn&#8217;t because people are already doing it through hacks. So, you know, it&#8217;s great to let people get ahead of you on this stuff. And once they do, adapt to them and implement features.</p>
            <p>So, summing up a bit, if you can increase the benefit and lower the barrier of entry, you should be able to you know, have more and more people participating on your site, and more people who participate on your site, the more people they attract to participate on your site, which is, you know, obviously a huge benefit.</p>
            <p>To give users a taste of what your site does, not only will they learn to do it, but they will create even a small level of commitment which will significantly increase their chances of actually participating on the site in the future. I think that&#8217;s something we&#8217;ll definitely be implementing on Digg, I&#8217;m not sure when but, you know, when we can.</p>
            <p>Expression. So, a lot of people have used their profiles and tying as many activities as you can to those user profiles. You know, it&#8217;s not just the &#8212; it&#8217;s not just a thing you do, it&#8217;s really important for creating trust and building connections on the site.</p>
            <p>Focusing on tension points, doing stuff like Satisfaction does, where they, you know, saw that tension point, came up with a really novel solution to deal with it.</p>
            <p>Be able to adapt to volume and frequency. I still think that&#8217;s a big open-ended question, something that we&#8217;ll be dealing with, you know, particularly as more and more people start joining social networks, you are dealing with more and volume issues, becomes very, very difficult.</p>
            <p>Paving the cow paths. Pay attention to what your community is doing and you will be able to see what kind of positive behaviors or what kind of negative behaviors are &#8212; they are going towards and be able to head them off in the path after they have already started.</p>
            <p>So, thanks very much. So I think I&#8217;ve left enough time for questions. I think we&#8217;ve got several minutes. So if anybody has questions &#8212; so &#8212; the slides are already up on the slide show so if you guys want to refer to them. So any questions? </p>
        </blockquote>
        <blockquote class="speaker_2_text">
            <p><cite class="speaker_2" >Q:</cite> It&#8217;s a little bit of minor point in the bigger context of what you are talking about. But one thing I thought when you dropped the most posted thing from Digg because, you know, there is people with only saleable amounts of digging in. </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3" >Daniel:</cite> Right. </p>
        </blockquote>
        <blockquote class="speaker_2_text">
            <p><cite class="speaker_2" >Q:</cite> Did it occur to you to switch like a monthly base thing. </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3" >Daniel:</cite> Yes. So we &#8212; we had toyed around with. We &#8212; we considered doing that and I think it&#8217;s possible we&#8217;ll implement something similar to that in the future, but I think even more likely I &#8212; I guess I &#8212; I planned to go into this, I &#8212; I guess I forgot, is what I&#8217;d see is even more likely is to go toward something like an achievement system. I don&#8217;t know if you are familiar with the Xbox 360, their achievement system. </p>
        </blockquote>
        <blockquote class="speaker_2_text">
            <p><cite class="speaker_2" >Q:</cite> Too familiar. </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3" >Daniel:</cite> It&#8217;s &#8212; well, exactly, everybody is familiar with it. Because it&#8217;s awesome, right. And so I had actually mocked up. I have &ndash; I have comps and actually asked our marketing person whether or not I could show them today and she actually told me no because apparently, you know, she doesn&#8217;t want to preempt any press if we ever implement this. But the &#8212; if &#8212; if we gave points for like, you know, you did five digs, get five points.</p>
            <p>You &#8212; you know, you berry destroyed that and ended up getting taken off the home page, good for you, you know, you found something bad, you know, 10 points for you. But the key to building a system like that is basically make it a real challenge, make it hard, but let lots of people get to the top level, you know, make it &#8212; kind of like World of Warcraft, you really got to invest yourself to get, you know, whatever level pilot in or whatever, I don&#8217;t play Warcraft.</p>
            <p>But, you know, make it difficult and a good challenge, you know, you don&#8217;t want to finish the game too early. You know, keep adding levels on the top. But I think something like that can be really, really valuable to Digg. I am not sure when and if we&#8217;d ever build that but I really hope we do at some point. </p>
        </blockquote>
        <blockquote class="speaker_2_text">
            <p><cite class="speaker_2" >Q:</cite> Thanks. </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3" >Daniel:</cite> Anybody have some question? </p>
        </blockquote>
        <blockquote class="speaker_2_text">
            <p><cite class="speaker_2" >Q:</cite> Do you think progressive registration would be the way forward, the way we take only small amount of data and start and gradually take more and more data until we collect all that we&#8217;d want from the user and you&#8217;d give them benefit for each level of detail that we get from them. </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3" >Daniel:</cite> Yes. So he is asking if &#8212; if progressive registration is a good way to go. I am not sure. I think that having, you know, maybe two levels of, you know, you can participate anonymously and then, you know, register, you know, and you actually get a full account, you know, we don&#8217;t need a whole lot to give you a full account. So, you know, we need your, you know, nickname. We need a password.</p>
            <p>And we need an email address. I think that&#8217;s, you know, the essentials. The &#8212; the one thing I am concerned about this and I&#8217;ve always been &ndash; we&#8217;ve talked about this for a while coming up with an anonymous digging on &#8212; on the site in this way that you can dig a bunch and then you know, to actually save them and make them really count, you have to register an account, is that you end up with these quasi account stages, right.</p>
            <p>So I always tell them, it&#8217;s a little weird eBay does this that you can watch an item as an anonymous person, but you can really watch it if you register an account because, you know, obviously if you switch a computer or if you lose your cookie, you lost your watch list. So it is always this weird thing, I feel like I did something but didn&#8217;t really. And so I am worried about that with Digg.</p>
            <p>So I think having two levels is &#8212; is certainly good, but you couldn&#8217;t call it progressive if what we did is ask for the bare minimums, you had a real account but then we did something like LinkedIn where you have, you know, hey you are only 30% the way you&#8217;ve done your profile, keep throwing it out, right, something like that. So you can call it progressive, but I think they&#8217;d actually have an account, you know, user name and password. So that&#8217;s why I consider like you are registered whether or not you&#8217;ve given any other information or, you know started, you know, a social graph or anything. </p>
        </blockquote>
        <blockquote class="speaker_2_text">
            <p><cite class="speaker_2" >Q:</cite> You guys change the UI at Digg quite often in pretty minor ways, not &#8212; because I am sure that would have a strong effect, but you make small changes quite frequently, I have noticed. Do you guys have a like a fixed release cycle with milestones or do you &#8212; do you tend to just push out small changes and adjust the flow as you see fit. </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3" >Daniel:</cite> Mostly the latter. We mostly, you know, build out stuff, you know, when it&#8217;s &ndash; when it&#8217;s done, when it&#8217;s ready, we get it out there kind of thing. Digg&#8217;s getting more and more formal about this stuff. The company is a lot, you know, when I started at Digg, I was the fourth person there I think. And, you know, we used to build stuff and send it live, you know, in seconds kind of thing which was &#8212; you know, it was fun and kind of reckless.</p>
            <p>But now things are a lot more structured than that. So we don&#8217;t move nearly as quickly as we did. But in terms of release cycles, we have kind of a 30 day cycle now going, but that doesn&#8217;t mean we&#8217;d necessarily release the data in the 30 days and small UI effect, you know, changes and, you know, other small changes get kind of a slipstreamed in between that.</p>
            <p>So yes, I definitely don&#8217;t want to get into the situation where we can&#8217;t make changes unless it&#8217;s at that 60-day point or something. I think that would be unfortunate, because we get a lot of advantage by pushing out the small pictures, small iterations, testing them, you know, if it didn&#8217;t &#8212; didn&#8217;t work we are moving it back or, you know, moving it another direction. I don&#8217;t want to end up where we are plotting too much and not able to make, you know, quick moves like that. </p>
        </blockquote>
        <blockquote class="speaker_2_text">
            <p><cite class="speaker_2" >Q:</cite> What sort of user testing do you do? </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3" >Daniel:</cite> Oh, that&#8217;s a great question. Mark Trammel actually who is here with me, you might want to grab him if you really want to get an in-depth answer. He is running our user testing at Digg. But we do well, we are getting better at it. We started &#8212; we originally were doing lots of like quick and dirty user testing, so we&#8217;d have a feature, you know, two-thirds, three-quarters way done.</p>
            <p>We&#8217;d drag in a bunch of people, give them some pizza and do task &#8212; we were largely doing task analysis. We were also doing some focus group testing particularly around like specific features. But now we are getting into a better &#8212; better situation where we were doing a focus group testing early in the project or, you know, even at the outside of the project to figure out what&#8217;s, you know, what people are anticipating us to do and then part of the way through we will do some user testing with other paper prototypes or visual comps and then near the end of the project, we will do proper task-based analysis on, you know, on working prototypes.</p>
            <p>So this is, you know, reasonably large feature. So we don&#8217;t test everything we put out, but we test a lot of things now and it&#8217;s &#8212; it&#8217;s stupid useful. It&#8217;s really, really useful. So, you know, we sometimes get so busy that it seems frustrating like oh, you know, I don&#8217;t think we have time to do user testing and every time we &#8212; we&#8217;ve done that, but we&#8217;ve, you know, suddenly said no, you know what, we&#8217;ll set Friday aside and we&#8217;ll just do a least some quick testing, we&#8217;ll get six people in. Every time, it&#8217;s been worth it.</p>
            <p>We&#8217;ve found, you know, an obvious problem that, you know, didn&#8217;t seem obvious at the time. And the great thing is these things are often really fucking easy to fix. It&#8217;s, you know, you are moving the button to left kind of thing and, you know, avoid a big problem and it&#8217;s great, you know. It doesn&#8217;t require a lot of effort and we get a ton of benefit out of it.</p>
            <p>I think that&#8217;s it for the time. Thank you very much. </p>
        </blockquote>
            
		  <p class="transcript_credit">Transcription by <a href="http://castingwords.com">CastingWords</a>, sponsored by <a href="http://www.opera.com">Opera</a>.</p>
	</div>

</div>


<?php include("../includes/footer.inc.php"); ?>