<?php 
	$title = "Tantek Celik";
	$section = "podcasts";
	include("../includes/header.inc.php"); 
?>

<div class="container clear">
	<div class="secondary">
		<ul class="speakers">
			<li><a href="/schedule/StevenJohnson.php" class="speak2">Steven Johnson</a></li>
			<li><a href="/schedule/AleksKrotoski.php" class="speak3">Aleks Krotoski</a></li>
			<li><a href="/schedule/DanielBurka.php" class="speak4">Daniel Burka</a></li>
			<li><a href="/schedule/MattJones.php" class="speak5">Matt Jones</a></li>
			<li><a href="/schedule/MattBiddulph.php" class="speak6">Matt Biddulph</a></li>
			<li><a href="/schedule/JoshuaPorter.php" class="speak7">Joshua Porter</a></li>
			<li><a href="/schedule/JeremyKeith.php" class="speak8">Jeremy Keith</a></li>
			<li><h2><a href="/schedule/TantekCelik.php" class="speak9">Tantek Celik</a></h2></li>
		</ul>
	</div>
	<div class="primary transcript">
	<h2>Social Network Portability </h2>
		<p class="transcript_credit"><a href="http://opera.com"><img src="/img/sponsors/opera.gif" alt="Opera Software" /></a>
		Transcription sponsored by <a href="http://www.opera.com/">Opera</a>.</p>
		
		 <blockquote> 
            <p> &#8230;You&#8217;ve heard a lot today about good design. I really enjoyed Daniel&#8217;s presentation, a lot of beautiful explanations and metaphors and pictures. So I am going to give you a little code today, some of that boring tech stuff, right?</p>
            <p>The first thing that I would like you all to know is the entire text of this presentation is released to the public domain, so you are welcome to use it, reuse it, re-purpose it, however you wish. The images that are included are all creative comments licensed by their respective owners.</p>
            <p>Just a really quick, sort of show of hands. How many of you have an idea of what you think are micro formats? OK, it seemed like, at least, half the people. How many of you have never used micro formats? A few folks. Just real quick here, folks.</p>
            <p>I asked Jim McCloud what he thinks microformats are, and that&#8217;s what he drew. So, that&#8217;s one idea, little dots on a card. He is this great cartoonist if you&#8217;ve seen him. He is quite witty.</p>
            <p>The best thing to do is just to see what do micro formats do. If we could connect to the Internet, we could see, but we&#8217;re going to skip that because we can&#8217;t. Here you go. One of the simplest examples is contact information, and I&#8217;ll just briefly outline what happens here.</p>
            <p>It&#8217;s that you go to a site; you go to a doctor&#8217;s site and say you want to copy the contact information; their phone number, their location, their address, maybe their <abbr>URL</abbr>. Each one of those gestures takes a user action. A copy, a contact switch onto a different application, a page; back and forth, back and forth. A dozen little user actions and all of those are marked up in a page as contact information.</p>
            <p>If you actually mark them up with this micro format called hCard, it enables the user to simply add that contact information to their address book with one quick click.</p>
            <p>As anyone here who is in business for themselves or a small start-up or looking at a consultancy, how many of you work in a small business or web design firm that always looking to get more business? Or more consultancy? Quick a few folks. And you probably have a contact page, right? How to contact us &#8212; maybe, a form; maybe, an email address; maybe, a <abbr>URL</abbr>.</p>
            <p>By adding hCard to your contact page, you can easily make it so that people can pick that up and add to that address book and, hopefully, lower the barrier to entry to actually getting in contact with you, give you direct economic benefit.</p>
            <p>We&#8217;re not going to dive into the micro format demo. You can check the presentation out online and check out these demos later. The one thing I will leave you with: How many of you run Firefox here? OK, most folks; at least, some of the time. How many of you have downloaded and installed the operator plug-in for Firefox? Wow, that&#8217;s quite a few.</p>
            <p>I would say that if you install one piece of software today, just search for operator and it will be one of the first few results in Google or whatever and install that on Firefox. You will see a whole different web.</p>
            <p>When you do a Google search, do a Google map search for, like, coffee near Brighton, England. You&#8217;ll find that the results come up. The businesses are listed, and all of those actually are marked up in hCard and you can add to your address book with one click, not just one business but all the businesses on the page. Sync that to your phone and then you can walk around and find those businesses. It&#8217;s a very different experience then in today&#8217;s web.</p>
            <p>We are going to talk about social network portability, and that&#8217;s a lot of multi syllable words, but what is the basic problem here we&#8217;re talking about? Daniel showed us Digg, and he showed us Pownce. We&#8217;ve seen other sites during the day, and we are going to see even more.</p>
            <p>Every one of these new social sites, and I think we&#8217;re getting a little better at this, but most all of them make you re-enter your personal info, re-add all your friends, re-turn off notifications.</p>
            <p>How many of you sign up for a site and then all of a sudden get email every day from that site? How many of you find this annoying? OK. Every new site that you sign up for you&#8217;ve got to turn that on. We don&#8217;t have some way of saying, &quot;I&#8217;ve turned it off for this site I signed up for. Can you just port that across for me?&quot; Or, maybe, some things I want to keep private; maybe, an actual physical address. Maybe, I&#8217;m OK putting my city public but not my specific street address. That&#8217;s something that I want to keep private, and that has to be re-entered every time as well.</p>
            <p>There are lots of things, and, maybe, you&#8217;ve got stalkers. Of course, this is the Internet. There is no such thing as stalkers or trolls or people that make your life unpleasant, especially on some of those popular sites, like Digg. This never happens. The system is in place.</p>
            <p>Flickr has done a really good job of having a block list. The question though is every time your site comes out you have to re-go to that site, re-find the people or wait for them to find you that harass you, if you have this problem, and re-block them. And so, it&#8217;s like this repeated little bit of a pain impulse every time, an electric shock kind of thing, every time you have to join this social network site.</p>
            <p>What if there was some way instead that we could say, &quot;Hey, just take my block list from Flickr. It&#8217;s there. I&#8217;ll let you log in using the Flickr authorization; go get it and reuse that. Wouldn&#8217;t that be excellent? The basic point is every time you do this there is this incredible amount of information you have to add, and Brian Oberkirk coined this the social network fatigue problem which is really obvious to anyone here who has added themselves and signed up for, at least, a few networks.</p>
            <p>In fact, I should ask you. How many of you signed up for, at least, three or more networks? Pretty much everyone. Five or more networks? Keep your hands up. Ten or more networks? Yeah. Twenty? I know some of you have. Admit it. After you signed up for that fifth or that tenthe .NETwork, you&#8217;re kind of like, &quot;I&#8217;m tired already. I don&#8217;t want to sign up for another one&quot;.</p>
            <p>What are the alternatives there? Well, we could all decide to go play in some walled garden where we say, &quot;Hey, this is our one network that we are just going to use and make everyone use that one&quot;, whether that network was called Friendster in the old days or, maybe, Orchid or MySpace or, maybe today, Facebook, the one popular network of today&#8217;s world. I think Facebook just advanced past MySpace in terms of total number of profiles.</p>
            <p>The fact that that&#8217;s changed over time should tell you something. There is no one sort of golden network that controls them all. They are going to turn over, whether because of fashion trends or whether because of generational changes whatever. We don&#8217;t know that&#8217;s the reasons. We leave that up to the anthropology researchers, but the reality is that it will turn over. There will come a day when Facebook is not popular. Of course, they&#8217;re not going to want to believe that or admit that, but neither did MySpace, neither did Orchid or neither did Friendster or <a href="http://sixdegrees.com/" >SixDegrees.com</a>.</p>
            <p>How many of you had an account on <a href="http://sixdegrees.com/" >SixDegrees.com</a>? This was like the social network site before any of these were invented back in the first integration of the web. They kind of experimented with a lot of this stuff.</p>
            <p>It&#8217;s not just a sign-up problem. How many sites or profiles do you have, and what happens when you, say, you get promoted in your job? You change your title, or you change companies. You move or maybe you change your icon. Maybe, you decide to change your icon to some goofy animate character. I&#8217;m sure none of you have done this in the last couple of weeks, right? [laughter] Right. How many sites do you have to update?</p>
            <p>If you are one of those people who raised your hand that you signed for 20 sites and you decide to change your icon to some animate character, you are just carrying this huge social network burden, this whole social network tax almost, this update tax.</p>
            <p>Ah, I&#8217;ve changed. I&#8217;m moving. I have to update 20 different networks. I forgot all of the different places I have to update. I&#8217;m sure there are places that still say that I work at Technorati even though I left over a year ago. I haven&#8217;t had the time to re-find all the places that I haven&#8217;t even bothered to log into for whatever reason. So, this is not just a sign up problem, but it&#8217;s also an update maintenance problem for your profile.</p>
            <p>It&#8217;s actually worse than that. It&#8217;s not just about you. Why are you in all these social networks? It&#8217;s also about your friends. The problem there is you meet someone at a conference. How any of you met someone here today? Maybe, hopefully? If you don&#8217;t know the person to your left or right, maybe at the break, say hello, introduce yourself.</p>
            <p>What&#8217;s your Twitter, right? Sort of today&#8217;s greeting. But then, maybe you find you have a bunch of things in common. You decide to talk. Or maybe you introduce yourself to someone and you find them highly offensive, and you&#8217;re like, &quot;I don&#8217;t want to deal with this person ever again. I&#8217;m going to go block them on some networks.&quot;</p>
            <p>How many friends&#8217; lists do you have to update? I&#8217;ve found this happens. Like almost every time you meet someone, there&#8217;s this little social network dance that you do. You&#8217;re like, &quot;Well, I&#8217;ll add you on Twitter. OK, well I&#8217;ll add you on Pownce. OK, well I&#8217;ll add you on Digg. OK, well I&#8217;ll add you on <a href="http://last.fm/" >Last.fm</a>. I&#8217;ll add you on&#8230;&quot; You know. And this sort of continues.</p>
            <p>And maybe there is a good quality, because it&#8217;s sort of like the social dance aspect going back and forth, back and forth. But after a few times of doing that, you get kind of tired of doing it. And maybe you just want to say, Look. This person&#8217;s great. I&#8217;ll even give them my whole Doppler travel profile access. Let them know exactly where I am. Or maybe my full Fire Eagle profile that gives exact <abbr>ICBM</abbr> geo coordinates.</p>
            <p>So this is another aspect of the sort of social network update maintenance problem. If you&#8217;ve got 20 sites that you&#8217;re doing, you&#8217;ve got 20 sites that you need to add people, if you really want to add them.</p>
            <p>This problem is not going to end. It&#8217;s not like tomorrow there&#8217;s going to be no more social network sites that come out. Are people going to go build applications that only run inside one of these walled gardens? Some people are picking that path, but most people aren&#8217;t.</p>
            <p>So, what we&#8217;re really talking about here, though, is the reason that users have to do this manually every single time is they don&#8217;t have really good control of the data in each one of these sites. So the goal here really is not just portability, but really it&#8217;s much more about user control. Putting the user in charge, empowering the user to do what they want with their information as easily as possible.</p>
            <p>So you want to move or syndicate, like I said, your profile information from one site to another. Your friends list of relationships. Perhaps even the fact that you have several sites that are all yours and you want to communicate that information to more than one site.</p>
            <p>So, Pownce has this feature that Daniel showed you, and we&#8217;ll go to that one more time, about other profiles, where you can list all these other sites that you&#8217;re on. Digg also has that feature, where you can list other sites that you&#8217;re on. But right now, today, I have to reenter that information.</p>
            <p>If I log into Pownce, I enter it. If I log into Digg, I have to enter it again. And this is by folks that have actually worked on both pieces. Wouldn&#8217;t it be nice if I could simply go to one site, maybe I enter it all on Pownce and go to Digg and say, &quot;OK. You know what? My Pownce profile already says what my other profiles are. Just go get them.&quot;</p>
            <p>So we need to basically acknowledge the fact that data that users put into our system is not ours. It&#8217;s theirs. Or another way to look at it is, maybe you sort of do a dividing line. Say, OK, give the user full control of their data, but let them keep a public section. Let them draw the line of what&#8217;s public and what&#8217;s private. I think that&#8217;s a very important design decision to make.</p>
            <p>And one of the things that, I think, Digg did that I want to call out as being really sort of groundbreaking, is they said, &quot;OK. Anything you upload to the site, comments whatever, that&#8217;s public, you&#8217;re releasing to the public domain.&quot; And this is just brilliant.</p>
            <p>This means that any site can remake use of mash up built applications on top of Digg using the public data on Digg without having to ask anyone for permission. And this is just brilliant, right? So, on Digg people don&#8217;t think much about it. They enter a few comments, maybe they enter a <abbr>URL</abbr>.</p>
            <p>But like why not do this with something like Twitter? Where you&#8217;re also entering one about 140 characters, which is probably about&#8230; The average Digg comment, I&#8217;m sure Daniel could probably tell you, is probably about that, too.</p>
            <p>So why not make that public as well? Everything you can make public more public domain, it becomes more portable. There&#8217;s less of a hassle. You don&#8217;t have to deal with the old folks. No offense to old folks.</p>
            <p>So, what we&#8217;re really talking about here is user experience. We&#8217;re really talking about making things easier for the users. That&#8217;s the most important thing that&#8230; Each one of us building our sites, we know that if we make things easy for users, we make them feel empowered, make them feel happy. So that they&#8217;re clicking that smiley face icon on GetSatisfaction when they&#8217;re commenting on some other thread.</p>
            <p>Then you know you&#8217;ve got loyal users. So let&#8217;s stop making it hard for them. New social networks, if you&#8217;re building a new one, ideally you should let users import and subscribe your profile information from some other site.</p>
            <p>You all raised your hands when I ask if you have three or more social network sites. Well I&#8217;m willing to bet that almost anyone you meet today is going to have at least a profile on some site somewhere, whether it&#8217;s Facebook or MySpace or Flickr or Twitter or wherever. So there&#8217;s always someplace where they can say, hey. Just start me off from here. Including their friends list and relationships.</p>
            <p>The interesting thing is that once you allow this sort of import/export with profiles that are portable, you actually allow the next step, which is interesting, which is syndication and thus subscription and making your profile&#8217;s updates live.</p>
            <p>So that when you update your icon on one site, you don&#8217;t actually have to go to 20 other sites and click an update or import button. Which is actually one step better than having to re-upload an image 20 times. But if they were subscribed to your profile, say to your Flickr profile with your Flickr icon, then they would just pick that up automatically.</p>
            <p>That&#8217;s the direction we really need to head with this stuff is, stop everyone trying to reinvent the users&#8217; data store for their information. It&#8217;s actually a lot of work. Why not just let them tell you, hey. I&#8217;m already here. Just subscribe from there. Maybe cache it for liability reasons.</p>
            <p>And once you do that, and once you actually let them import their networks and represent their networks publicly as well, and connect them all up, you actually get a network of social networks, which we can call a social inter-network.</p>
            <p>Now, this is all fine and great. This is sort of like what Daniel was talking about, un-attaining them. If I could only make things trivial for the users [indecipherable] that made it frictionless for the users to sign up on various sites, it would be awesome. Right?</p>
            <p>But we all have work to do. We all have jobs to do. We all have design considerations. We all have clients that are saying, &quot;Oh. Make the logo bigger.&quot; Right? I&#8217;m sure that never happens.</p>
            <p>The key here though is to make sure that whatever techniques we use to do this are actually easy for sites to adopt as well. And this is one of the core principles of microformats is to make things easy and accessible to web designers and web authors and not just developers. So that anyone that knows <abbr>HTML</abbr> can pick up and learn and use microformats.</p>
            <p>How many of you have hand-authored some <abbr>HTML</abbr> at some point? OK. There&#8217;s pretty much everyone raising your hand. And if you haven&#8217;t, I&#8217;m willing to bet that you could sit down in about five minutes, learn to not just write a little bit of <abbr>HTML</abbr>, but to write a little bit of microformats. In fact, you could even just copy and paste what you&#8217;re going to see in the presentation.</p>
            <p>So a lot of what modern web designers are already doing these modern practices of using semantic class names, using plain old semantic <abbr>HTML</abbr>. Which we&#8217;ve termed, or abbreviated to this term posh, which I&#8217;ve taken to understand has a bit of a cultural zing when it comes to the UK. But hey, no matter what word you pick, you&#8217;re going to end up upsetting someone, right?</p>
            <p>Another aspect is something that Daniel talked about for users, which is that if they put in a little bit of work, they should get at least some benefit out. And that helps encourage them to do more work.</p>
            <p>Well that&#8217;s true for us, too. If we can do a little bit of implementation and get some benefit immediately on our sites for our users, it&#8217;s very encouraging. Rather than having to do a big chunk of code, and do some massive implementation of some massive <abbr>API</abbr> before you get to see anything.</p>
            <p>And that&#8217;s another important aspect of microformats. That by keeping all these building blocks modular, by having little pieces you can implement one at a time and get benefits one at a time, it makes it easier for you to say, &quot;Oh, I&#8217;ve got an extra half day or I&#8217;ve got an extra hour. Let me implement this one piece and see what happens.&quot; So I think that&#8217;s really important.</p>
            <p>It&#8217;s also really important to not ask sites to do a lot of new things. Almost every site that has users already has a profile <abbr>URL</abbr> for that user. We should not ask them to make another profile, &quot;My Portable Profile <abbr>URL</abbr>&quot; as a separate <abbr>URL</abbr>. That&#8217;s ridiculous. We should be able to use the existing <abbr>URL</abbr>s that they have.</p>
            <p>We shouldn&#8217;t ask them to learn a new format. We should be able to work with the current content that sites publish. When you looked at the Digg profile that Daniel was showing, or the Pownce profile, any of those, each one of those profiles shows slightly different information, or a <a href="http://last.fm/" >Last.fm</a> profile.</p>
            <p>Those are all based on design considerations. And I&#8217;m here to tell you that that&#8217;s the right consideration to use when you pick what content to show and publish. Not because you want to make it portable, but because you already know what the user wants to see, what they&#8217;re comfortable publishing. And that is much more important than some abstract notions of portability or programmer convenience. So we want to work with the current content that&#8217;s published.</p>
            <p>How many of you know about the dry principle? OK, a few folks. So dry stands for don&#8217;t repeat yourself. And this is a really important principle we try to emphasis in microformats. What it basically means is that if you have a piece of information, the more times you duplicate it in the content that you publish, the greater the chance that its going to become out of sync.</p>
            <p>Now this gets really bad when one or more places that you publish that information is actually invisible &ndash; is not visible to the user. Whether it&#8217;s in the comments in your <abbr>HTML</abbr> code or it&#8217;s in metadata, invisible metadata, Meta tags or maybe even some random <abbr>XML</abbr> file. OK. Chances are that data is going to become out of date as compared to what&#8217;s visible on the users profile page.</p>
            <p>We actually de-emphasis doing that. We say &quot;Don&#8217;t bother putting stuff that&#8217;s invisible data in invisible places, because it will become out of date.&quot; I mean you think &quot;Well, we are all just getting it from a database&quot; right. Doesn&#8217;t matter. Everything that requires updating. Everything requires a little piece of code to generate.</p>
            <p>Probabilistically, we will break at some point in time, right. Code breaks. They are bugs. That&#8217;s just the way this thing works. And so, when push comes to shove and you have ship a new version of the site, what do you check? You check what the site looks like, OK. If you have to make some tweak the last minute &ndash; you may actually break the stuff that&#8217;s invisible because you are not checking it.</p>
            <p>When you do a user test, are the users looking at the invisible data? No, they are looking at the visible data. So that&#8217;s the part you are caring about, the manipulating, and the users see and tell you about. If there&#8217;s a problem on your profile page, they are going tell you and get satisfaction because it&#8217;s visible. Not because it&#8217;s invisible.</p>
            <p>OK. So here&#8217;s an example of a simple profile that might exist on some site. This is my friend Chris Messina. He&#8217;s worked on various different open standards. So here you&#8217;ve got a bunch of information. You&#8217;ve got his name, his photo, notes, blog hyperlink &ndash; and this is what makes an hCard. Which is essentially the vCard standard. Which every one of you has at least one device that it supports, probably two devices, translated into <abbr>HTML</abbr> &ndash; into semantic <abbr>HTML</abbr>.</p>
            <p>So there are several examples here. I am not going to bother clicking on them. But if you clicked on those in the presentation, you could see that depending on the site you go there are actually all marked up. And in fact even the speakers for this conference and last years conference are all marked up with H-cards, and you could add them to your address book if you choose to.</p>
            <p>The key here&#8217;s to recognize that you&#8217;ve got a name, an image, some notes and then a link to his blog. These are the most common elements of profiles. Another common thing you see, and this is what the Pownce interface of other profiles illustrates is that users hyperlink their identities. Almost every social network site today has a field &ndash; enter your <abbr>URL</abbr>, enter your home page, enter your blog, right.</p>
            <p>And a lot them, in fact perhaps even most of them now, are actually marking that up. They are marking it up with a standard called <abbr>XFN</abbr> <code>rel=&quot;me&quot;</code>. And they are pointing to their blogs. They are pointing to their social network profiles. They are pointing to their Pownce. Maybe they are pointing to their OpenIDs, OK.</p>
            <p>And they are either doing that maybe on a site like Pownce that says &quot;Here&#8217;s an interface to do it.&quot; Or they are doing it on their own blog. WordPress is a nice link manager that lets you add links to your blog and say &quot;This is me.&quot; Or maybe they are just coding it themselves.</p>
            <p>However they do it, they are basically forming a structure like you see there. So the next building block is list of friends that you have. And it looks like just a bunch of icons, but actually, these are all hyperlinks to their profiles, right. The friend icons have images there, and their names are actually in the image alt tag [<i lang="la">sic</i>] as well.</p>
            <p>So there&#8217;s quite a bit of semantic information there that you can actually mark up with hCard for the link icon name and use <abbr>XFN</abbr> for relationship. Even just marking up as rel=[?]content. If all you have is a friend system that adds friends yes or no, even that helps make that visible.</p>
            <p>OK, so what are the steps to actually make this work? So there&#8217;s two basic steps. You want to publish microformats in your social network profiles as much as you can, and the friends list. And then you also subscribe to them. Let people bring their stuff in and take their stuff with them. So help them form a flow of their information. Help them import information through your system.</p>
            <p>So hCard on user profile pages, <abbr>XFN</abbr> rel=&quot;me&quot; are hyperlinks to the blogs and home pages. hCard and <abbr>XFN</abbr> friend list&#8230;now if you have a separate friends page besides their profile page, you need to rel=&quot;me&quot; to that page as well. And if you multiple friends pages, say, because they have like, you know, 5000 friends or something. Maybe they are Robert Scoble. All right you are not going to save 5000 friends on one page. Then you actually have to use a combination of the <abbr>HTML</abbr> 4, rel=next and previous values with the rel=&quot;me&quot; value. And the rel attribute since it&#8217;s a space separate set of values. You can do that, no problem.</p>
            <p>So the second piece, right. Let the user subscribe to their information and bring it in. You want to let them subscribe to their profiles. Bring in their icons. Bring in all that stuff. Subscribe to their friends lists and the names of friends. So that if they add someone on Twitter, they should automatically get the option to add them on Pownce. If they add someone on Flickr, they should automatically get the option to add them on Digg or Doppler.</p>
            <p>So there&#8217;s a lot more to describe detailing these steps. It&#8217;s all described on the microformats wiki. Well I am going to show you just a tad bit of code. Again using the same example. I am hoping that most of you can read that. How about the folks in the back? OK, yes. All right. So what we&#8217;ve got here, we are saying &quot;OK, this whole thing you can mark as up as a DIV.</p>
            <p>And we use the class vCard which comes from the vCard standard or <abbr>RFC</abbr> 2426. We mark up as a name with FN, which stands for formatted name. Mark up the image, that&#8217;s with photo with classicals photo. Mark up the note with classicals note. And finally the link to his blog, we mark it with a classical <abbr>URL</abbr> which is part of the hCard standard, saying this is a <abbr>URL</abbr> for Chris.</p>
            <p>We are also marking with rel=&quot;me&quot; which is part of <abbr>XFN</abbr> to indicate &quot;Hey this blog of his over here is also part of his identity, that is same as his profile.&quot; Its part of the same person. OK, that&#8217;s it, that&#8217;s literary all you have &ndash; that&#8217;s the mark up you have to add. You probably have some mark up like the green. You have a few class values and rel value and that&#8217;s all the work you have to do to mark up a profile.</p>
            <p>Now we talked about Pownces other profiles feature. Well here&#8217;s the mark up behind that. Literary all that they had to do was add rel=&quot;me&quot; to each one of those links. That&#8217;s it. It&#8217;s not that difficult to do and probably takes you less than a minute to add to your template, and all of a sudden you are supporting it.</p>
            <p>The key thing here is that for this to actually work properly there has to be some symmetry. So they link out from their Pownce profiles to all these different places, to their Flickr to their Technorati et cetera. From those locations the users will link back to their Pownce profile or their blog, whatever they consider their central hub of identity. And most users pick one spot that&#8217;s like &quot;Hey this is me. This is who I am on the web&quot;. And I would link out from here and link back into here.</p>
            <p>Most people use their blog for that, but you can also use your Pownce profile or your Digg profile, or any number of profiles that now support this other profiles feature which is getting much more popular.</p>
            <p>Finally, the friends list. OK. Very similar to the profile you got a classical vCard for each person. You got classicals <abbr>URL</abbr> on the <abbr>URL</abbr> to them, and now <code>rel=contact</code> because you are linking to someone else, not another page that represents yourself. You are saying, &quot;This profile over here is a contact for me&quot; right.</p>
            <p>This next thing going on is kind of interesting with the image element. Since we&#8217;ve got the photo and their name on the same element, we can actually use FN for the formatted name and the photo on the same element, and that works great.</p>
            <p>And again, same thing, you just add a few class names and a rel value and you have made your friends lists portable. All right, save a separate friends page, like that &#8216;view all&#8217; link over there, OK. Add rel=me meets that, because that&#8217;s part of your larger profile. Anytime you have a profile page that has various information about the user [indecipherable] and you start separating it down to one or more pages, for design consideration, space considerations, performance considerations, maybe even mobile considerations, right.</p>
            <p>You want to keep your pages small enough to load quickly and efficiently on a mobile device. Just link to rel=&quot;me&quot;. And of course, you want to be sure you link back from the friends page to the profile page with rel=&quot;me&quot; as well, so that, that link relationship of identity is confirmed. And then if you paginate with previous and next links, you simply add rel=&quot;me&quot;to both of those.</p>
            <p>And you might as well go ahead and add the semantic <abbr>HTML</abbr> &quot;next&quot; and &quot;prev&quot; as well. So that you know when you&#8217;re navigating through the entire list&#8230; A crawler can come by and say, &quot;Oh yeah, this is all part of the same set of things, &quot; and it can know when it&#8217;s done.</p>
            <p>So, who supports this? Lots of companies now. It&#8217;s been a little bit over a year since I first put up a lot of these recipes for what you should do to support social network portability and tons of companies are supporting this now. So check the Microformats wiki for the latest, but you&#8217;ll find that there are easily&#8230; I think we&#8217;re above the 100-million mark at this point as far as social network profiles that support hCard. And the number of <abbr>XFN</abbr>- and hCard-supporting friends lists is huge.</p>
            <p>So publishing is one thing, but what about the signup process? This is an area that I think is something that definitely could use a lot of innovation. If you look at what Daniel was showing you with Digg&#8212;they&#8217;re going to make it easier for you to sign up with Facebook Connect or with your OpenID&#8212;I want to actually emphasize that the first thing you should support is to import from the open social web, from the social web.</p>
            <p>From the fact that there&#8217;s more profiles that support hCard than there are&#8212;across all these different sites&#8212;than there are Facebook profiles. Than there are MySpace, or&#8230; Any other specific site has now been exceeded by the total set of open profiles that are out there.</p>
            <p>Something that Get Satisfaction has done is they actually create an interface here where you can just click a link and say, &quot;Oh yeah, I know my Flickr, I can type that in.&quot; I don&#8217;t think it&#8217;ll load, but let&#8217;s see what happens&#8230; And it tries to get your profile.</p>
            <p>As the network&#8217;s going to be slow for us, right?</p>
            <p>It tries to get your profile but then when it finds it, it fills in all the fields for you and gives you a checkbox that lets you subscribe to the profile as well. And that&#8217;s particularly powerful. This is implemented today on Get Satisfaction. So if you create a new Satisfaction account, you don&#8217;t need to upload a new icon. You don&#8217;t need to update it when you update it on your other profiles.</p>
            <p>So it&#8217;s the most widely-supported profiling format, like I was telling you. There are more hCard users than any one site. And the question is, can we actually take steps toward making the signup process as simple as possible? Can we actually achieve this goal of having maybe a single field where you just enter your <abbr>URL</abbr> and name and sign up?</p>
            <p>And from that, you can import the user&#8217;s hCard, you can get their profile, you can get their nickname, which they can use as a login name, right? You can get, perhaps even their OpenID. All this information can be published with a single place.</p>
            <p>And maybe even their email address. You don&#8217;t actually need to add a whole bunch of new fields and get them to sign up. Maybe you want to send them a default password. Or maybe you don&#8217;t even need a password because you just use their OpenID to let them sign in.</p>
            <p>It is possible, and I think this is not one of those unobtainable things, this is one of those points we&#8217;re going to approach and we&#8217;ll see&#8212;like, within the next year&#8212;we&#8217;ll see sites that let you sign up with a single field.</p>
            <p>Now, I mentioned OpenID. This is an area where there&#8217;s been a lot of work, and a lot of work with InfoCard and a bunch of other different identity systems, and what I want to say is: there is a word of caution here to keep in mind. Full disclosure.</p>
            <p>Be a little bit aware of third-party authentication, you guys, because when a user comes to your site, it&#8217;s your trust that you&#8217;re trying to imbue the user with. You&#8217;re trying to get the user to trust and hopefully be faithful to your site.</p>
            <p>So assume that the user gives your site some trust&#8212;maybe a friend told them about it, maybe they got highly recommended&#8212;you don&#8217;t want to lose that. And a lot of these authentication systems require you to go to some other site, log in, or do something, and then come back to your site.</p>
            <p>The challenge with that is that there actually are some phishing issues with that kind of a back-and-forth interface. Now, we&#8217;re all fairly advanced users here that understand what we&#8217;re doing, so it&#8217;s not that much of a big deal for us.</p>
            <p>But if you show an average person how to log in on some of these sites with their OpenID or whatever, they get really confused. &quot;Why am I on this other site now? Why is it bouncing me back and forth?&quot; There have been some advancements to that interface, so I&#8217;d say definitely take a look at what that works.</p>
            <p>There&#8217;s even some problems with just signing up, what we call man-in-the-middle attacks. I&#8217;m not going to go into much detail with these because you can click on it. These are lengthy studies. There&#8217;s even a <abbr>CHI</abbr> 2006 paper, &quot;Why Phishing Works&quot; that goes into a lot of these scenarios of how phishers actually take advantage of the fact that, if you see something that looks like a login page, you&#8217;ll most likely enter it in and trust it.</p>
            <p>So I&#8217;d say consider implementing OpenID in addition to importing and subscribing to hCards on the web. But insist on not sacrificing the user experience.</p>
            <p>If you look at how OpenID logins are implemented on sites today, it varies widely. Lots of different approaches to doing it. Some have icons in various places, some have a separate login page, there&#8217;s all kinds of different complexity that folks have introduced with OpenID logins that I think is unnecessary.</p>
            <p>It&#8217;s not OpenID&#8217;s fault. I think the problem is that by looking at it as, &quot;Hey, we need to tout this feature, we need to tout support for this standard&quot; you end up walking down this path of designing something that&#8217;s more complicated than it needs to be.</p>
            <p>The best standards are the ones that are invisible to the user. Data should be visible, the technologies should be invisible. It should work like magic. You shouldn&#8217;t have to know that there&#8217;s hCard underneath the covers. You shouldn&#8217;t have to know that there&#8217;s OpenID underneath the covers.</p>
            <p>You should just be able to sign in with your <abbr>URL</abbr>, your profile <abbr>URL</abbr>. And either it&#8217;ll work, because it&#8217;s an OpenID <abbr>URL</abbr>, or it&#8217;ll bring in your profile information because it&#8217;s got hCard, or your signup form will say, &quot;Hey, thanks for your <abbr>URL</abbr>, now enter the rest of the information we need.&quot;</p>
            <p>There&#8217;s no reason to put the little orange button there that says &quot;<abbr>RSS</abbr>&quot; that, back in the old days, would just display gobbledegook to the user. Let&#8217;s avoid this sort of techno-jargon pollution of our interfaces and instead focus on keeping the interfaces simple for the user.</p>
            <p>All right. So, find friends. This is another common area that, once you&#8217;re supporting, publishing all this information, you also want to let the user find their friends on various different sites. Right now, you go to a lot of these sites&#8212;like Digg, or Pownce, or even Dopplr&#8212;and you have to pick which site to import your friends from.</p>
            <p>Well, on my Dopplr I actually tell it, &quot;Hey, I&#8217;m also <a href="http://tantek.com/" >tantek.com</a>.&quot; And from there, it knows my Twitter is <a href="http://twitter.com/t" >twitter.com/t</a> because it&#8217;s all linked with rel=&quot;me&quot;, it&#8217;s all linked from my Pownce, etc. But it still asks me, &quot;What&#8217;s your Twitter account name?&quot;</p>
            <p>There&#8217;s actually no reason for it to ask me, it has the information. It knows my <abbr>URL</abbr>, my OpenID, <a href="http://tantek.com/" >tantek.com</a>, that I can log in with. It could simply either crawl that, get the rel=&quot;me&quot; links and get the equivalent profiles, and know, &quot;Oh, OK, I know you&#8217;re also &#8216;t&#8217; on Twitter, I&#8217;ll use that for you.&quot; Or it could call a Google Social Graph <abbr>API</abbr>, which I&#8217;ll discuss a bit. This is something that Dopplr could improve.</p>
            <p>Pownce actually does do this, which is kind of nice. I think Pownce&#8217;s implementation of this; they&#8217;ve been improving pretty continuously with slight UI tweaks along the way. So if you actually enter in your other profiles on Pownce&#8212;just to show off your little badge on your profile page&#8212;when it comes time that you decide you want to import your friends, it uses that information, which is one less step for the user. Any time you can improve the user interface by removing a step for the user, you&#8217;ve made it that much&#8230; You&#8217;ve reduced the friction by that much and helped the users use that much more.</p>
            <p>The problem is, I&#8217;m always adding new folks to Twitter. So, do I have to go back to Pownce all the time and say, &quot;Hey, check my new friends again.&quot; This is part of the whole social network tax that I have to pay every time I join a new network. Instead, it should syndicate it.</p>
            <p>Pownce should automatically say, &quot;Hey, we&#8217;ve noticed that you&#8217;ve added a bunch of friends to Twitter, do you want to add them?&quot; Or maybe I trust to add everyone on Twitter to my Pownce and I want a checkbox that says, &quot;Always add everyone that I add&quot; so that I can know that when I add someone on Twitter, it&#8217;ll automatically add them on Pownce.</p>
            <p>Now, this is something that I think Pownce has fixed, but a lot of services make this assumption that, well, if you have a friends list on one site, with their aliases, they&#8217;re probably the same on the current site because people tend to use the same username across different sites. While that tends to be true, it also comes with a bunch of false positives.</p>
            <p>Another problem is that all these sites require you to import your Twitter friends, then your Pownce friends, then your Gmail addresses, then your Yahoo addresses, etc., one at a time. You don&#8217;t actually have to do that, necessarily. I mean, sure, you can give the user that kind of fine-grained control, but just like that slider image that Daniel showed you, you&#8217;re kind of copping out a little bit from a user interface standpoint.</p>
            <p>Better instead to find your friends across the web and this is an exceptionally powerful thing that right now is implemented only on a napkin.</p>
            <p>OK. There it is right there. So what this diagram is illustrating, this napkin drawing is illustrating &ndash; and I think a lot of good designs start as napkins &ndash; is say I have an account on Dopplr, and I have linked to my blog or my Pownce. That&#8217;s the left-hand side. That&#8217;s all my identity, that left-hand oval, right?</p>
            <p>Then I also link from my blog and my Pownce to my Flickr. Now my Flickr, let&#8217;s say I&#8217;m friends with Jeff Feem, which I happen to be &ndash; I&#8217;m following him on Flickr, following his photos &ndash; and his Flickr links to his blog which also links to his Dopplr.</p>
            <p>So you can actually follow the realm elinks, determine that my identity on Dopplr includes my blog includes my Flickr, notice the fact that OK well Jeff&#8217;s identity&#8230; That on Flickr I&#8217;m friends with Jeff and that his identity there consolidates with his blog and with his Dopplr. Then determine 100% certainty that hey you can suggest that you know Jeff on this site you should add him on here.</p>
            <p>No false positives. This scales across different sites. So you can just call Google Social Graph <abbr>API</abbr> &ndash; which they launched in February of this year, which indexes all this information &ndash; to find out what are the other sites I&#8217;m on. You just give it a <abbr>URL</abbr>. It gives you a backlist of <abbr>URL</abbr>s. Google&#8217;s cached all these links already, so they can just tell you. And who are my friends across sites?</p>
            <p>These are <abbr>API</abbr> calls you can make today to Google to calls information. You don&#8217;t need to call each site separately. You can call Google once or twice and get this information for people across the web. That&#8217;s where this needs to go. More work done for the user with less effort.</p>
            <p>So why are companies supporting this anyway? Well, some folks actually do the right thing it turns out. Do the right thing for the user. Get more users sooner. You reduce friction &ndash; this is an obvious one, we all know this &ndash; you reduce friction for sign-up, people sign-up more.</p>
            <p>A lot of folks are saying, but I don&#8217;t want my information to go out. I want to protect all the information in our little silo. The thing is if you actually publish your user&#8217;s information that&#8217;s public with hCard, with <abbr>XFN</abbr> and all that, what you&#8217;ve now done is become a high quality publishing location for that user where they can syndicate out their data. They can trust it just like they would trust their blog that syndicates out their feed as <abbr>RSS</abbr> or Atom.</p>
            <p>So you actually build more loyalty by your users by opening up their data and letting them repurpose it and mash it up with other sites. Because if they update their icon on Flickr and make their satisfaction depend on it, they&#8217;re more likely to keep going to their Flickr account.</p>
            <p>This last one is one we&#8217;ve seen over the last year. Hcards and <abbr>XFN</abbr> now dominate in numbers above any other specific social network silo. This is a natural effect of any open standard that the network affects when two sites implement it, there&#8217;s more incentive for a third site. There&#8217;s more incentive for a fourth site. Metcalfe&#8217;s law insures that this is going to continue to happen.</p>
            <p>Finally you want to outgrow the competition, right? But before we jump too far into outgrowing the competition, I want to at least mention the anti-patterns. The things that you should avoid doing. So there are a bunch of social portability non-goals and dangers.</p>
            <p>This is the most important one. Do not ask for usernames and passwords to other sites. You&#8217;re teaching for&#8230; Gmail, Yahoo mail, all these sites, these actually have <abbr>API</abbr>s now. You don&#8217;t need to ask for users Gmail or Yahoo mail. Because when you do this, you are teaching users to be phished.</p>
            <p>A random site comes along and says hey let&#8217;s import all your contacts into this thing that keeps track of your favorite books or whatever. Then all of a sudden it turns out that it actually takes over your Gmail, uses your Google Checkout account, takes your money from there or whatever. It&#8217;s a bad habit to teach users.</p>
            <p>The second one which is highly related to this. Unfortunately a lot of the same sites do this. They get your Gmail, Yahoo mail address and say well we just want to check to see who else is on the site, but they don&#8217;t do that. They actually go and email everyone on your address book.</p>
            <p>How many of you have received an email invite from a friend from a social network, followed shortly by an email saying, &quot;Oh I&#8217;m so sorry.&quot; Or a Twitter. Quechup did this last year to great distain, and I think fortunately there was enough feedback mechanism with Twitter and all these other sites that when sites are doing this now, they are getting called out for it sooner and sooner.</p>
            <p>In fact we have a little bit of a hall of shame page on our Wiki called social network anti-patterns that you can go see Goodreads &ndash; spams your address book &ndash; Quechup, Facebook &ndash; asks for your password, your Gmail &ndash; Nsyght, ShareThis, Twitpic login, etc., all these sites. So I encourage you if you find sites that do this anti-pattern, please go ahead and add them to that Wiki.</p>
            <p>OK. The final thing to avoid. Avoid violating user expectations. This one&#8217;s important. Users when they sign for a service, when they give their email address, their expectations today is that email address is private. They don&#8217;t expect that that email address is going to be shared even implied to be shared.</p>
            <p>So if you do something like say consolidate their identities across different sites by looking up their email address, by search &ndash; just because you can do something doesn&#8217;t mean you should &ndash; you will violate the user&#8217;s expectations. So obviously don&#8217;t publish the user&#8217;s email. Most sites don&#8217;t do that.</p>
            <p>But less obvious, don&#8217;t even publish a unique cache of their email because that enables third parties to consolidate their identities across different sites in ways that the users do not expect. They don&#8217;t expect that site A will share their email even in sort of a un-equified form with site B or with site C. So when that happens, they&#8217;re like, &quot;Oh my gosh. How did you know that? &quot;</p>
            <p>This is the creep out factor we talked about. It&#8217;s all nice and wonderful to make things seem automatic and easy, but if it seems creepy, you&#8217;ll scare the user. They&#8217;ll not want to use your site. They&#8217;ll be like, &quot;Why do you know this about me. I don&#8217;t trust you any more.&quot; Then you&#8217;ve lost that user. That&#8217;s no good. So avoid publishing email and unique email caches.</p>
            <p>What next? Implement today based on public data. Keep up with updates on the Microformats Wiki, social networks portability. Add your site to the Wiki as you implement each one of those little pieces. As you implement hCard profile, there&#8217;s a page to say we implemented hCard profiles. As you implement [indecipherable] to their blog or home page, there&#8217;s a list for that too. Add your site there. As you implement an <abbr>XFN</abbr> friends list or an hCard or <abbr>XFN</abbr> friends list, add those on.</p>
            
            <p>Finally, this is an area that has just gotten working pretty recently which is OAuth support for incorporating private data. How many of you use Flickr? A lot of folks here. How many of you use some support of Flickr up loader application or something like that? Do you remember the first time you signed up? You had to go to Flickr and say I&#8217;m going to give this application permission to upload, right? Vaguely? Then you came back to this application and said you&#8217;ve approved this application.</p>
            <p>That&#8217;s basically what OAuth does but in an open way, open standards way and is now supported by Google for the Gmail contacts <abbr>API</abbr> and supported by a lot of other companies.</p>
            <p>So if you support this, both as an endpoint and as a consumer &ndash; which means that you provide an OAuth interface to allow other sites to access your user&#8217;s private data with their permission and while you&#8217;re looking to import information from another site you try to access it via OAuth and get their permission &ndash; then you can now import not just their public information but their private information. I believe there&#8217;s a library being released pretty soon for this. Is Glenn here? Glenn? Has that library been released? </p>
        </blockquote>
              <blockquote class="speaker_2_text">
            <p><cite class="speaker_2">Glenn:</cite> Yeah, this morning. </p>
        </blockquote>
              <blockquote class="speaker_3_text">
            <p><cite class="speaker_3">Tantek:</cite> This morning? So Glenn Jones of Madgex. This morning there&#8217;s been a library released, open source library released to import your contacts via OAuth from any site or publish. Take a look at that link. Look at OAuth support, and you&#8217;ll find it there.</p>
            <p>So this entire presentation, by the way, it was microformats. The text is Public Domain as I want to reiterate. If you have any questions, join the conversation. The Hash microformats channel on IRC. <a href="http://irc.freenote.net/" >Irc.freenote.net</a> is the best place to start. If you click that link you&#8217;ll find the IRC Wiki page on the microformats Wiki. Thank you.</p>
         </blockquote>
            
		  <p class="transcript_credit">Transcription by <a href="http://castingwords.com">CastingWords</a>, sponsored by <a href="http://www.opera.com">Opera</a>.</p>
	</div>

</div>


<?php include("../includes/footer.inc.php"); ?>