
<?php 
	$title = "Aleks Krotoski";
	$section = "podcasts";
	include("../includes/header.inc.php"); 
?>

<div class="container clear">
	<div class="secondary">
		<ul class="speakers">
			<li><a href="/schedule/StevenJohnson.php" class="speak2">Steven Johnson</a></li>
			<li><h2><a href="/schedule/AleksKrotoski.php" class="speak3">Aleks Krotoski</a></h2></li>
			<li><a href="/schedule/DanielBurka.php" class="speak4">Daniel Burka</a></li>
			<li><a href="/schedule/MattJones.php" class="speak5">Matt Jones</a></li>
			<li><a href="/schedule/MattBiddulph.php" class="speak6">Matt Biddulph</a></li>
			<li><a href="/schedule/JoshuaPorter.php" class="speak7">Joshua Porter</a></li>
			<li><a href="/schedule/JeremyKeith.php" class="speak8">Jeremy Keith</a></li>
			<li><a href="/schedule/TantekCelik.php" class="speak9">Tantek Celik</a></li>
		</ul>
	</div>

	<div class="primary transcript">
	<h2>Playing the Web: how gaming makes the internet (and the world) a better place</h2>
		<p class="transcript_credit"><a href="http://opera.com"><img src="/img/sponsors/opera.gif" alt="Opera Software" /></a>
		Transcription sponsored by <a href="http://www.opera.com/">Opera</a>.</p>
		
		<blockquote>
		<p> Hello! Yes, my name is Alex Krotoski. I&#8217;m slightly nervous, I have to admit. I&#8217;m either going to stay here or I&#8217;m going to run around. So, see if you can catch me if you can. My first question&#8230; Actually, no. First is an admission. The column that I write about is about computer games. I am a gamer for MySims and I was wondering if I could just ask you guys out there who has played the game ever? </p>
		 <p> Wow! Look at that! Thousands of hands. Keep them up, right. Of you, all of you pretty much in the audience, who here still plays games? Oh&#8230; dropping of hands. Well, I&#8217;m not going to make any assumptions. My third question is who here plays games and works in the games industry? Oh! Look at that! Gone! Oh, golly, there&#8217;s two! Hello! Three, four! Four? OK, there&#8217;s a couple. There&#8217;s actually more people than I thought would be here from the games industry because the web industry and the games industry do not meet and it&#8217;s the freakiest thing and it&#8217;s something we&#8217;re going to talk about later, something we&#8217;re going to try and hammer home the entire time because it&#8217;s fascinating, particularly because web people are obsessed with games.</p>
            <p>I remember when I first met Andy, I was giving a talk about games, a girl geek night, and he said, &quot;Oh, I work in the web industry and I&#8217;m really interested in games!&quot; and I went, &quot;Oh God, yeah, that makes total sense!&quot; He kept saying, &quot;You know, you can play&quot; and buzzword this and collecting that and all these kind of stuff and I was like, &quot;Yeah, totally! I can totally see where that&#8217;s coming from.&quot;</p>
            <p>Speaking with my gamer friends, they&#8217;re like, &quot;Nah, I&#8217;m not interested. We don&#8217;t really need those web types because we do it ourselves&quot; and I&#8217;m like, &quot;Whoa!&quot; But surely there&#8217;s an amazing amount of synergy there, that&#8217;s going on there, where you&#8217;ve got people who are interested in games and people who have a phenomenal audience and if you bring the two together, you might actually get something that&#8217;s beautiful. Again, more on that in a little bit.</p>
            <p>But the reason I think that web people are so interested in games is for that special, special feature of games. Oh, I didn&#8217;t do it. Oh, yes! Stickiness&#8230; Oh yes, games are incredibly, incredibly compelling, phenomenally compelling. People lose their lives. In some cases, some people die playing games.</p>
            <p>Now, of course, we&#8217;re not interested in creating that kind of phenomenon very often in the web. It depends on what you&#8217;re into. Do you know there&#8217;s a lot of stuff out there in the Internet? Whatever! But the reason why people who are developing web is because of stickiness and stickiness is important because&#8230; Oh, the &quot;Big A.&quot; Yes! Tantarah&#8230; Advertising! And this comes from Seed Camp. They put bubbles up with the lovely graphics, up about what is it, how is it that people who applied for Seed Camp, how do they plan on making their money? The vast majority of people, as you can see, said, &quot;Advertising.&quot;</p>
            <p>Now, how do advertisers get their worth? Well, that&#8217;s that stickiness thing. That&#8217;s those eyeballs, that&#8217;s page impressions and that&#8217;s the only way that we can actually, as web people, looking at metrics, that&#8217;s the only way that we can actually say, &quot;Right worth.&quot; There you go. Here you go McDonalds, here you go eBay, here you go Amazon. There you go, that&#8217;s your worth. You&#8217;ve got eyeballs.</p>
            <p>So, out of that, out of this stickiness, out of this relationship between games and web has come a phenomenal number of flash games that have cropped up and marketers use them for everything from McDonalds to Skittles to presidential campaigns and they stick them up in their website and they say, &quot;Brilliant! Fantastic! That&#8217;s our game. We&#8217;ve done it.&quot; But what they&#8217;re finding is that people would just engage with those games for a brief amount of time as long as that&#8217;s an interesting brand and then they&#8217;ll move on.</p>
            <p>That&#8217;s actually not what we&#8217;re interested about here today because we&#8217;re talking about the social stuff, we&#8217;re talking about the stuff that goes on around the games and what it is that game designers do to help to create that social web. Oh&#8230; technology is hard.</p>
            <p>So, it&#8217;s about the graphics really, isn&#8217;t it? That&#8217;s what it&#8217;s about. It&#8217;s all about those sexy, sexy graphics! Grand Turismo here, very sexy game, very sexy graphics. But you know what? On the web, you guys are able to imbed content. You guys are able to put video, real live video with real live people up into your systems. You don&#8217;t necessarily have to create these phenomenal artworks that people play with in games. Great example, Rick Ruben, a game from the PlayStation, absolutely brilliant game!</p>
            <p>These are the graphics, a really badly drawn rabbit and a really badly drawn level and you as the player just had to go like that. It was so compelling and I was there for hours and hours and hours creating my own levels, sharing them with people and saying, &quot;No, you&#8217;ve got to try this, this is absolutely amazing!&quot; It&#8217;s a music, rhythm, action game, I loved that anyway. So, it was a music, rhythm, action game. The animation here didn&#8217;t matter, it was all about that oft overused word in web circles, &quot;play.&quot;</p>
            <p>So, now that we know that graphics don&#8217;t matter, let&#8217;s think about something else that everybody thinks that games have, the &quot;story.&quot; It&#8217;s all about telling a story, it&#8217;s all about the narrative. It&#8217;s about drawing people in and saying, &quot;Right, let me lead you along this lovely garden path with these wonderful characters and we&#8217;ll all embrace and dance through the mind fields of Half Life 2, for example, if you wish.&quot;</p>
            <p>Well, here&#8217;s a little something and the game developers in the audience could probably confirm this, the story, traditionally, has been the last thing that&#8217;s been stuck on to the back of a game system. The story and the script are the last things that are actually thought about when you&#8217;re developing a game. Again, it turns out that it&#8217;s all about play. That&#8217;s what compels people to stick with the game for quite frankly an unreasonable number of hours. </p>
            <p> That&#8217;s from my Nintendo DS and that&#8217;s Advance DS and I&#8217;d just like to say that that&#8217;s not playtime but I&#8217;m not going to point out the person whose playtime it is. But, anyway, this is the something special, this is what brings people, this is what forces people and ensures that people will stick. It is, unfortunately, I have to say, the play.</p>
            <p>So, games are actually part of what I like to call and what I&#8217;ve heard, this is a brand new term for me and I think it&#8217;s brilliant, the &quot;Experience Economy&quot;,  which is just a fantastic way of saying here is something that&#8217;s really fun, let&#8217;s make it sound really dull. Also, in the Experience Economy are roller coasters. Brilliant fun! Experience Economy! Theme parks, brilliant fun!</p>
            <p>Anyway, that&#8217;s what games fall into. Games are part of emerging the player, creating the space and allowing the player to explore, to experience those assets, to pick around in the back of what&#8217;s going on in GoldenEye on the N64. You saw the film, now you can be James Bond, now you can go behind those little bits and you can see that guy who&#8217;s all frozen. Now, you can actually make the story yourself and you can actually experience it. The Uber Movie, the Super TV, they are these things that you can actually take part in and suddenly you are the action hero.</p>
            <p>Now, arguably, this is difficult to do when you&#8217;re dealing with a website. I appreciate this. But, over the next couple of minutes, what I&#8217;m going to do is I&#8217;m going to talk about three systems of development that games developers and designers bring into their games that help to create and help to ensure that they&#8217;re quite social, that they are these compelling products. I&#8217;m also going to counter each of these arguments with an example of the web and I&#8217;ll get to why in a little bit.</p>
            <p>The three systems I&#8217;m going to talk about are the controlled systems, the enabling systems and then the psychological systems. I am an academic, which means that I like to break things into theories and I like to put things into boxes. Especially the psychologists, we like to put things into boxes. So, these are the three boxes, this is the theory that I&#8217;m going to explore.</p>
            <p>The first one is the controlled systems. Now, these are the bits that the designers can actually control. These are the bits that the designers say, &quot;This is game!&quot; Slap. Thank you very much. This is what they actually build into things. These are the explicitly gamey things. First&#8230; Oh, this sucked when I was a kid, man! Especially because you couldn&#8217;t actually save in Super Mario Brothers, so you had to get there and you thought, &quot;Oh! Another castle, another castle!&quot; No, I&#8217;m sorry. Another castle, you have to keep going. No dinner for you. You can&#8217;t even put it on pause because if you do that, you&#8217;re going to run out of battery. Oh, it&#8217;s all going to go horribly wrong. Suffice to say, I&#8217;ve never actually finished Super Mario Brothers for MySims.</p>
            <p>In the controlled systems, the first one I want to talk about is that they designed games and dangled carrots in front of people&#8217;s eyes. Your princess is in another castle, but congratulations, you&#8217;ve come this far! You&#8217;ve invested this much time. We&#8217;ve given you clues, we&#8217;ve dribbled the experience&#8230; Please, keep playing. No, really, come with us on the rest of the journey. We&#8217;re going to make it really, really interesting and really, really compelling.</p>
            <p>They give more if people would just contribute that little bit more and that&#8217;s obviously a unique game thing, isn&#8217;t it? Well, OK, it may not be as sexy as princesses, but the web does this too and they ask people to give more and more and more of themselves, of their information, for example, of their time. They say, &quot;If you are an expert user, then your blog will feature on the front of WordPress. If you want to contribute to this conversation, then just give us a little bit of information about yourself.&quot; Of course, the more invested you are and the more that you&#8217;ve explored, the more involved that you&#8217;ve become and the more you&#8217;ve found of interest and of use in these web systems, the more likely you are to give.</p>
            <p>It&#8217;s the exact same thing with games. For those psychologists in the audience, this is also known as &quot;Cognitive Dissonance.&quot; You can look it up later in Wikipedia for the answer. The second thing I want to talk about in this system is openness. Games developers, this is from Liberty City, the most recent GTA game. Games developers are obsessed, and, in fact, gamers. The reason for this, kind of a synergistic relationship here, obsessed with this idea of openness, creating these spaces that I want to go into that warehouse. See that one over there? It looks like some Lee Harvey Oswald place. I want to go up there and I want to go hang out there and I want to see what that&#8217;s all about. I want to feel, as a player, that I can go absolutely anywhere and I can interact with anyone. I can speak with anybody and I can do anything in this space.</p>
            <p>That&#8217;s one of the things that&#8217;s certainly coming out of a lot of new console and PC games, is this notion that it&#8217;s an enormous world that you can buy into. You can feel part of that, you can engage yourself with that, you can get immersed in that and have a sort of sense of presence in these places. These are called &quot;Sandbox games.&quot; There is a very fine line between a sandbox game that&#8217;s a little bit too much and one that&#8217;s just perfect. Unfortunately, it&#8217;s very difficult to know.</p>
            <p>Grand Theft Auto San Andreas, for example, or Tomb Raider 3, these are games that are considered way too big and it takes ages to get from one end to another and you&#8217;re not really sure what to do. But ultimately, these types of games are better in terms of value, in terms of investment, in terms of engagement for the player, for the gamer, than a game that is known as being played on rails. It has nothing to do with rails designers, it&#8217;s just what it&#8217;s called. Ah, I like my little web joke there.</p>
            <p>Anyway, so anybody who&#8217;s wandered around the web is also aware that the web is an enormously open, vast, expansive space and the rabbit holes that I&#8217;ve fallen down doing my PhD have been really interesting. I mean, really fascinating and phenomenal and I&#8217;d lose days and months. In fact, almost five years going down these rabbit holes and searching for something that&#8217;s really interesting right then. I need to know all about that. I don&#8217;t want to know about that, I need to know all about that.</p>
            <p>So, the web itself is an enormously vast and expansive and open environment that people can get involved with. The challenge, and this is the challenge that the games designers seemed to have done a really good job, especially those in successful games, is to create a funnel that feels wide enough that people are in, an open enough environment, but that directs them down the path where they actually want to go.</p>
            <p>To create that relevance in games is called an &quot;ending goal.&quot; In the web, it might be finding out information or exposing people to lots and lots of different types of things that they didn&#8217;t already know about. So, that is the real challenge for web developers when you&#8217;re dealing with this vast expanse of the Internet, like you also want them to drift off the path and find out weird things about paper crafts occasionally, for example, which is what I spend a lot of time doing instead of social psychology.</p>
            <p>The next system that I want to talk about is the enabling system. The enabling system is a system in which there are emergent systems&#8230; Right, let&#8217;s see if I can get this right. There are emergent systems, systems which emerge or activities which emerge or senses, sensibilities, social phenomena which emerge based on the creations that the people, that the developers and the designers have made. The developers and designers have enabled&#8230; Do you see where I&#8217;m going with this? They&#8217;ve enabled. I&#8217;ll move on, yes [laughs].</p>
            <p>First up, community. Everybody here knows about community because that&#8217;s what the web is all about, especially Web 2.0 or Social Web or whatever you want to call it. It&#8217;s all about the community. Of course, this is from Alice Taylor. Actually, should I say her name? Her sublimity has been completely destroyed, Alice Taylor who writes for Wonderland and I&#8217;m not sure who Munchhausen is. They are in World of Warcraft and they had a dinner party which they arranged for their guild members.</p>
            <p>What&#8217;s absolutely fascinating is that while web people have had community basically since the openness, since one Internet connected another Internet to the Internet in between and across, between MIT and Stanford and Berkeley, there was already community there in the web. It facilitates community because ultimately it is two people or multiple people communicating. It just so happens to be behind the screen.</p>
            <p>Games, they may have had some community. They may have had some practice, some communities of practice ahead of time. But it really hasn&#8217;t been until they&#8217;ve started to explore the web, until they&#8217;ve started to get involved with things like World of Warcraft, with things like Everquest or Ultima, going back a little ways. These are the things that have really brought to bear this notion of community for the games industry and it&#8217;s only since places like this that I&#8217;ve started to see special community managers, people who are actually hired in to manage the community.</p>
            <p>Of course, web people have been thinking about this for a while. But, ultimately, the community that&#8217;s built around the games, it&#8217;s built around this interpersonal interaction that&#8217;s based around a property, it&#8217;s based around a thing that is the game or the sense of the belonging that is built around the fact that you are on big or you&#8217;re involved with something that happens to be something that everybody rallies around. I&#8217;m not laboring that point anymore, you know what I&#8217;m talking about.</p>
            <p>So, out of community comes what I was alluding to before when I talked about the dinner party, the pictures look brilliant, they all got naked, they were dancing. It just sounds completely mental. As somebody who&#8217;s avoided World of Warcraft like the plague, no pun intended, it looked like quite a lot of fun and almost got me, almost got me.</p>
            <p>Anyway, out of the community comes social value. This is the next part of this system. These are the features, these are the brands, these are the characters and occasionally even the stories, if I say stories, that are generated by the communities that are based upon the things that are developed by the designers, things that are created by the designers. Out of this comes the creative output that&#8217;s completely separate to what the designers created. This is, for me, the most exciting stuff. This is where you find real money transfer, people spending $15, 000&#8230; Well, supposedly spending $15, 000 in a source program for an online-based ballgame in Second Life.</p>
            <p>Is that allowed, Linden Lab? Are the allowed to sell that on eBay? I don&#8217;t know. There was a bit of a question mark about whether you&#8217;re actually allowed to sell these types of content from any of the online games.</p>
            <p>This is a phenomenal example of this because suddenly you&#8217;ve got a community rallied around an object that&#8217;s virtual that has a value, that has a real social value for the people who are involved. Again, these things have been developed by the designers. These things have&#8230; I&#8217;ve said &quot;value&quot; far too many times already. The relics, the assets, that are generated by the people who design these games, whether they&#8217;re based on the economic models that have been put into place, these are the things that people engage with and that people play with. Things in games like game FAQs. People spend a lot of time developing FAQ systems. How to get through, walk through systems for how to get through games.</p>
            <p>These are some of the things that I&#8217;m talking about that help to develop and to create that social value. As I mentioned, you don&#8217;t have to create a brand. You don&#8217;t have to create an economic model around your website in order for this to happen. These are just some the websites, <a href="http://amillionpenguins.com/" >amillionpenguins.com</a>, which was a wiki novel where people just got together and they thought, &quot;Brilliant! OK, we&#8217;re going to be supported by Penguin and Penguin&#8217;s going to have nothing to do with this except to provide the platform. Let&#8217;s just play around and see what comes out of it.&quot;</p>
            <p>Pac Manhattan, obviously inspired by a game, but using the real world space and creating a space where people who are involved and invested with location-based gaming could get together and to create something that they were able to. Find Satoshi comes from a game that&#8217;s called &quot;Perplexity&quot; and that happened to span loads and loads of websites, even the dreaded Zombies and the Werewolves and all that kind of stuff. You can see this again and again where creative output is actually coming.</p>
            <p>I love this, this is from data mining. God, the amount of data mining stuff that&#8217;s on is absolutely amazing and they&#8217;re not visualization stuff. The lucid, playful visualization stuff that comes out of web development is phenomenal and that&#8217;s where people are playing in this space. This, I don&#8217;t know if anybody&#8217;s seen this before, but this is how Robert Scoble, where Robert Scoble fits into Twitter. As you could tell, he&#8217;s in the middle. Unsurprising, based upon the people that he&#8217;s connected with. But this is how people are playing online already.</p>
            <p>The last system is psychological. As I mentioned, I&#8217;m a social psychologist so these are close to my heart. The first is obviously the relationship between the avatar. These are all from Second Life. So, obviously, in that space, you have an environment in which everything is personalizable and you can actually create whatever you want. So, the notion, the idea of having an avatar that represents, that quite literally represents something about yourself, it&#8217;s quite an explicit connection.</p>
            <p>But what I find fascinating was maybe about four years ago. We started to see in traditional console gaming and PC gaming, we started to see more of this role-playing element wherein a character started to develop assets, whether it was muscles or superior problem-solving skills or was able to run further based upon the actions and the activities that people in the game did. Now, this wasn&#8217;t necessarily based on a database that was built online. This was actually stuff that was built into the actual game itself.</p>
            <p>Through this role-playing system and through this engagement, the players started to recognize that they can actually play with this and they could start to create an avatar, they could start to create the character that leads them through the game, that represents them through the game and have it more closely represent themselves. This personalization has been an absolute revolution, it&#8217;s been absolutely amazing to witness, to see how this type of thing started to really encapture and enrapture games designers and developers. Of course, that&#8217;s impossible in the web industry, isn&#8217;t it?</p>
            <p>It couldn&#8217;t possibly have that much personalization. Literally everything in the web is personalized. MySpace, a really easy example. All of these are different. There&#8217;s me in the middle. Hello! With different colored hair.</p>
            <p>The web offers phenomenal personalization opportunities, but that&#8217;s a relatively recent thing. It used to be really the only thing that could represent you was perhaps a pseudonym, something that you used, a tag that you use when you are in a chat room or perhaps an image. For the hardcore role players, they would be able to develop characters that would transfer around.</p>
            <p>But with things like this, you&#8217;ve got explicit things, almost as blatant as a teenager&#8217;s bedroom saying, &quot;This is who I am.&quot; These are the bands that I like. This is what I do. This is who I am. With this combined with something like Open Idea or any of these other types of applications and theories and possibilities of bringing a massive, widespread identity, something that follows you and then says, &quot;Right, come on, I&#8217;m going to say to people this is who you are based upon what you do, based upon the person that you want to represent.&quot;</p>
            <p>This is something that&#8217;s actually compelling and it&#8217;s something that&#8217;s being realized on the web. Finally, something that&#8217;s much more of a sort of basic psychological urge, and this is something that I think the web community is really focused on, the idea of collecting stuff. It seems to me when I do speak with web developers, they talk about, &quot;Right! OK, we need to create a system wherein you collect a certain number of points and then you&#8230;&quot; There seems to be a real emphasis on that as a way to bring gaming into the web.</p>
            <p>Indeed, this could be part of that funnel part of that goal direction in games and also on online environments, but, partially, why it works so well is because it&#8217;s a sense of challenging yourself. It again comes back to that reflection of identity of who I am. I&#8217;ve collected this many coins, that means I&#8217;ve done this many things. Of course, something like &quot;P Mug&quot; can be played. It can be played to collect things. You can go out and you can seek to earn certain things, certain badges, on the basis of, &quot;Right, I&#8217;m going to specifically try to not use Google for seven days so that I can get this badge.&quot;</p>
            <p>At the same time, you don&#8217;t have to do that. You could happily traipse along and have this visualization of who you are and your identity. You can have this online and you can have this represent yourself. You don&#8217;t have to actively play it, but you can actually go out there and you can actually collect these things.</p>
            <p>So, how have game developers done this? I know that there&#8217;s a lot of research. I know there&#8217;s a lot of human/computer interaction work. I know that there&#8217;s a lot of user experience work. That&#8217;s what so much of this stuff is focused in web and it&#8217;s fascinating, absolutely phenomenal. So, it seems only logical and only likely because what games developers do is they create these compelling, engaging feedback systems, these beautifully-designed feedback systems which work and they work so beautifully. They work so well that they do compel people for 344 unreasonable hours on the Nintendo DS [laughs].</p>
            <p>So, surely, they should engage with these types of things as well. Well, interestingly enough, this is what I&#8217;ve learned. This is a gamer&#8230; It&#8217;s a bad representation of a gamer, I do appreciate. I&#8217;m also a gamer [laughs]. I hope I don&#8217;t look like that right now. Last night, partied, who knows? This is a gamer and what I&#8217;ve found is that the gamers tend to make the games designers, that there is really a loop, a feedback loop, that there isn&#8217;t as much focus in games development on things like UI, on things like HCI, on theories of engagement and involvement.</p>
            <p>These things have emerged because the games designers were gamers themselves and they&#8217;re developing games and they&#8217;re developing products that appeal to them because in their gut they know it&#8217;s a good game, they know it plays well. It&#8217;s a phenomenal qualitative, it feels utterly unquantitative. From the games developers and the designers that I&#8217;ve spoken with, they say, &quot;Oh, I didn&#8217;t actually really know that there was an industry called Human-Computer Interaction.&quot;</p>
            <p>I&#8217;ve spoken with some programmers who are really annoyed by that because as part of their degree they have to study Human-Computer Interaction and then they come into the games industry and the designers say, &quot;Right, right! So we&#8217;re going to build this giant tree and the tree is going to have things that drop off and it&#8217;s going to be brilliant!&quot; and they go, &quot;But how does that respond? How does that relate to the player?&quot; What&#8217;s fascinating is that they&#8217;ve done it, they seem to have cracked it. It&#8217;s worked in a beautiful and compelling way.</p>
            <p>But, truly, it&#8217;s because you&#8217;ve got this cycle of gamers making games for other people who play games. In contrast, this is the audience of the web developers. As you have, as you already have the skills and as I hope I&#8217;ve conveyed, as you already have all of these techniques that you haven&#8217;t necessarily had to apply, the playful things that you haven&#8217;t necessarily shoehorned into your development practices, they just emerged, perhaps for the same way, the same reasons that game developers have created the products that have emerged.</p>
            <p>There&#8217;s a couple of challenges. The first challenge, it would be great, really beautiful&#8230; I mean, just like, oh, summit, Gorbachev and Reagan. Oh, beautiful! It would bring everybody together, if we get web people to actually speak with games people. Apologies to the games people in the audience, but I find that in environments like this, in places like this where there is something, there is so much that can be given back to the games industry from what we&#8217;re talking about today, from the things that you can talk about when you&#8217;re having coffee, there&#8217;s very little games representation and I don&#8217;t know why.</p>
            <p>Some of the people I&#8217;ve spoken with have said, &quot;Well, they&#8217;re more interested in what we can give to them.&quot; I don&#8217;t actually agree with that. I actually think that you guys already know how to make stuff that&#8217;s compelling. You already know how to make stuff that&#8217;s playful because you&#8217;re already doing it. So, there&#8217;s other things that you are able to give back. So, the first challenge is talk to them.</p>
            <p>The second challenge is that the games industry at the minute is doing a really beautiful job of creating compelling&#8230; I just keep saying that word but it&#8217;s so true! Creating compelling entertainment that&#8217;s cross media, that&#8217;s cross platform. They&#8217;re using cameras, they&#8217;re using music, they&#8217;re using all different types of things that aren&#8217;t necessarily just merchandising opportunities or marketing opportunities. They&#8217;re actually integrating all these things across different platforms and using them in really fascinating and some quite innovative ways. But if only the web people could say, &quot;Right, well, I&#8217;ve got all these! See this baggage that I&#8217;m bringing with me? I&#8217;ve got all these!&quot;</p>
            <p>Well, if we meet in the middle, then we&#8217;re able to create something phenomenal, something beautiful and something that could potentially revolutionize multi-platform entertainment forever. Thank you very much!</p>
		</blockquote>
		 <blockquote class="speaker_3_text">
            <p><cite class="speaker_3" >Alex:</cite> Questions? I will duck. I&#8217;m sorry if I have offended the games people. </p>
        </blockquote>
        <blockquote class="speaker_4_text">
            <p><cite class="speaker_4" >Man 1:</cite> With games coming out, things like Spore and Little Big Planet, would you say that the games industry is kind of almost trying to learn from us some things as well? </p>
        </blockquote>
        <blockquote class="speaker_3_text">
            <p><cite class="speaker_3" >Alex:</cite> Well, what&#8217;s fascinating about Little Big Planet is that the producer on it, the sort of in-house producer at Sony, not at Media Molecule who&#8217;s the company that&#8217;s actually developing it, comes from a web background. And I know certainly at places like EA in Gilford which used to be Criterium, they&#8217;re working on a lot more of this kind of social networking stuff. Spore? Not necessarily because Spore comes from Will Wrights and Will Wrights has a background of developing simulated games that are quite compelling to wide audiences.</p>
            <p>But in terms of something like Little Big Planet where you do have that notion of almost a MySpace for user-generated gaming content, I&#8217;d definitely say for sure, for sure, for sure, they&#8217;re starting to engage with that. Certainly, you can see that with things as well. Examples like the Xbox gamer score. That&#8217;s another example of a social network and bringing this type of knowledge from the web into embracing that. But, unfortunately, it really does feel like it&#8217;s few and far between and I don&#8217;t understand why the twain. They don&#8217;t actually just hang out occasionally.</p>
            <p>There are five games companies, five international games companies in Brighton and there&#8217;s only a couple of representatives here and it just seems fascinating to me that there isn&#8217;t more of a relationship there. Yeah? </p>
        </blockquote>
        <blockquote class="speaker_5_text">
            <p><cite class="speaker_5" >Man 2:</cite> Have you seen any effort to kind of&#8230; When I look at the games industry, I see people locked into certain platforms. That&#8217;s part of the problems, they&#8217;re trying to cross from web to Xbox. I remember earlier on, I&#8217;m a DS fan myself and I keep looking to saying, &quot;It&#8217;s got WiFi.&quot; It&#8217;s got WiFi. I&#8217;ve got to be able to do something besides get my ass kicked on Mario Kart. </p>
        </blockquote>
        <blockquote class="speaker_3_text">
            <p><cite class="speaker_3" >Alex:</cite> [laughs] </p>
        </blockquote>
        <blockquote class="speaker_5_text">
            <p><cite class="speaker_5" >Man 2:</cite> There&#8217;s got to be a way to make these things interact. I keep on waiting for the Wii and the DS to try to start talking to each other because you can do these compelling things, you can take parts of them with you. Is anybody doing more stuff like that to try to bring these different aspects into the games? </p>
        </blockquote>
        <blockquote class="speaker_3_text">
            <p><cite class="speaker_3" >Alex:</cite> Well, I&#8217;ll have a little history tour now. The thing that I found, the most innovative thing I&#8217;ve ever seen in my entire life at games was on the Dreamcast, the dearly departed Sega Dreamcast. The Sega Dreamcast was an ill-fated machine that was so ahead of its time, like so ahead of its time that we&#8217;re only actually now seeing the realization of some of the things that the Dreamcast put into place then and actually seeing it now in the mainstream games console. Well, things&#8230; exactly! You&#8217;re doing that. I know exactly what you&#8217;re talking about. </p>
        </blockquote>
        <blockquote class="speaker_2_text">
            <p><cite class="speaker_2" >Audience:</cite> [Off mic] </p>
        </blockquote>
        <blockquote class="speaker_3_text">
            <p><cite class="speaker_3" >Alex:</cite> Exactly! So, that&#8217;s an example. You&#8217;re asking why there isn&#8217;t more integration. So, back in the day, oh&#8230; early 2000s, early 000s&#8230; the Dreamcast was released with much funfair. We&#8217;ll all play together, it&#8217;s connected to the Internet. Whoa! You can play Choo Choo Rocket, which is a little maze game. You could create your own content for that and you could share it. You could play Fantasy Star online, which was a massively multi-player online game, using this home console and it was absolutely amazing.</p>
            <p>But what it also had, which I think alludes to what you&#8217;re talking about, is a relationship between something that you could take away. The memory card on the Dreamcast, the big, chunky Dreamcast controller, was called the &quot;visual memory unit.&quot; You plugged it in and it acted like a memory card on any traditional games console, it saved your game. But what it also did was it had a little visual, it had a little screen. So, you could take that out and it acted like a very small games handheld machine, about the size of a modern mobile phone [laughs] and not like this big clunky one anyway.</p>
            <p>You could take that away and you could play a pared down version. You could play a pared down version of the game that you&#8217;ve saved on your machine. So, if you were, for example, playing&#8230;I think there was one on Sonic, one of the Sonic games that was released on there, you could play something on Sonic, bam, bam, bam, brilliant, beautiful graphics, whatever. You could take it away &ndash; sitting in the bus, sitting in the tube, sitting staring out the window, wherever you are where you&#8217;ve got a little bit of time and you want to play with it &ndash; you could take it out and you could play a sub-game. That sub-game, when you then transferred it back to the Dreamcast and back to that saved game, enhanced your character, enhanced the game that you&#8217;d actually played around with.</p>
            <p>Now, we&#8217;re starting to see that. I think in the last Nintendo system, the Game Cube, you were able to connect that. There were relationships there, as well. I know they have been talking about having relationships between the Playstation three and the PSP. We haven&#8217;t really seen the realization of those things.</p>
            <p>One really, really interesting area that I&#8217;d wanted to put in here, but wasn&#8217;t sure how quite to fit it in, is that when the Xbox 360 was announced at E3 &ndash; the Electronics Entertainment Expo &ndash; several years ago, they said that you&#8217;d be able to connect the Xbox 360, a Microsoft machine, with the Playstation portable, the PSP, with the iPod, with the&#8230;and you&#8217;d be able to actually interact and engage with that. So, that cross-platform opportunity is there. I don&#8217;t know how the realization of that has come about.</p>
            <p>There&#8217;s not much play &ndash; I think of it more as a storage system. Yes, I think there is more of that and those cross-platform issues&#8230;it&#8217;s a challenge, it&#8217;s an obstacle to leap over, but the facilities and the opportunities exist there, yes. </p>
        </blockquote>
        <blockquote class="speaker_6_text">
            <p><cite class="speaker_6" >Woman 1:</cite> Hi there. What do you think created this kind of divide between the games industry and the web industry? Do you think it&#8217;s because of a platform or broadband issue, or because the games industry is more based around fantasy, or something, and it&#8217;s not really taken seriously and the web is kind of a real environment? </p>
        </blockquote>
        <blockquote class="speaker_3_text">
            <p><cite class="speaker_3" >Alex:</cite> I don&#8217;t know where you are so I can&#8217;t &#8230;. </p>
        </blockquote>
        <blockquote class="speaker_6_text">
            <p><cite class="speaker_6" >Woman 1:</cite> Down here. </p>
        </blockquote>
        <blockquote class="speaker_3_text">
            <p><cite class="speaker_3" >Alex:</cite> Oh, there you are! Staring vaguely up.</p>
            <p>I think it&#8217;s because they developed in two different ways. The games industry really developed out of a kind of&#8230;.especially in the UK, the British games industry is amazing, how it developed. It&#8217;s been so, so innovative, but it primarily developed out of a bedroom-coder sensibility where most of the people just thought, &quot;All right, I&#8217;m going to try this. All right, it worked &ndash; I&#8217;m going to sell it to my mates. OK, I&#8217;m going to sell it to more m&#8230;.Oh, my God! Look at all those people who bought my game! I can&#8217;t believe that!&quot;</p>
            <p>So it was kind of a pocket over here and it really hadn&#8217;t intended to be something much larger, whereas the web industry has always been about connecting people. So there&#8217;s been a different type of person who&#8217;s come to this space because they haven&#8217;t been creating things specifically for game interaction, they&#8217;ve been creating things specifically to connect people.</p>
            <p>While I did say that the web and the communities have always happened on the.</p>
            <p>Internet, it really hasn&#8217;t been until very recently that it&#8217;s been widespread and people have actually really been able to engage with the web. And I think that now that we see people really engaging with the web, we&#8217;re going to start, hopefully, seeing more crossover.</p>
            <p>Certainly, people who make games &ndash; [aside] there&#8217;s this side, that side &ndash; are very much about interacting with the machine and, increasingly, they&#8217;re starting to play around interacting with other people. The web used to be about interacting with machines and now it&#8217;s more about interacting with other people. So, if the twain can meet, then that would be brilliant.</p>
            <p>In terms of how the games industry is perceived; it is unfortunately perceived as&#8230;well, that picture I showed you. I&#8217;m not really breaking any stereotypes here, unfortunately. It&#8217;s perceived as a child&#8217;s plaything, unfortunately. I think that ultimately people don&#8217;t recognize the depth and breadth of what is possible and what&#8217;s being done in the games industry. It isn&#8217;t just about fantasy, it isn&#8217;t just about shooting people, it isn&#8217;t just about racing fast cars, there&#8217;s a lot of other fascinating things that are happening &ndash; the content that&#8217;s happening in the games industry. It&#8217;s also not just about military endeavors either. There&#8217;s a lot of fascinating things in the games industry that are out there that I think haven&#8217;t been communicated well enough. That&#8217;s a marketing issue and that&#8217;s a whole.</p>
            <p>Other talk.</p>
            <p>So, what he&#8217;s saying is that the barrier is to do with the notion of open standards, open development practices in the web, versus very proprietary elements in the games industry.</p>
            <p>Hopefully we&#8217;ll start to see that changing as more independent development starts to come out &ndash; I&#8217;m adding that bit, by the way. [laughs] Hopefully we&#8217;ll start to see more of that open-standards concept breaking out as more independents start to create their products, as well. </p>
        </blockquote>
        <blockquote class="speaker_4_text">
            <p><cite class="speaker_4" >Man 1:</cite> Hello. I just wanted to go back&#8230;.[interrupted] </p>
        </blockquote>
        <blockquote class="speaker_3_text">
            <p><cite class="speaker_3" >Alex:</cite> This is the last question, by the way, so I&#8217;ll speak with you later. </p>
        </blockquote>
        <blockquote class="speaker_4_text">
            <p><cite class="speaker_4" >Man 1:</cite> Oh, sorry, whoever was going to ask one.</p>
            <p>I just wanted to go back to where you said there was a feedback loop between games players becoming games designers. Do you think there&#8217;s a problem with people preaching to the choir? I think the problem we have a lot on the web is that, yes, we&#8217;re trying to target a very large audience, but one of the reasons we have all these research practices in place is to make sure that we target people who are not like ourselves, rather than designing products based for ourselves.</p>
            <p>Actually, what you do see a lot in the games industry is people making games they want to play rather than people making games an audience wants to play. It&#8217;s a problem that&#8217;s there on the web too and I think it&#8217;s kind of dangerous.</p>
            <p>I was wondering if you could comment on ways the games industry impacts the web industry at getting around that, and if either of them could learn anything from each other about it. </p>
        </blockquote>
        <blockquote class="speaker_3_text">
            <p><cite class="speaker_3" >Alex:</cite> How they&#8217;re not preaching to the choir? </p>
        </blockquote>
        <blockquote class="speaker_4_text">
            <p><cite class="speaker_4" >Man 1:</cite> Well, no. How they&#8217;re getting around this issue. How they are learning how to avoid doing that. </p>
        </blockquote>
        <blockquote class="speaker_3_text">
            <p><cite class="speaker_3" >Alex:</cite> In the games industry, in particular, there&#8217;s been a lot of research recently trying to expose people who aren&#8217;t traditional gamers and say, &quot;These people also play games!&quot; I wrote a paper about women and gaming. It was unfortunately titled &quot;Chicks and Joysticks.&quot; [laughter] That was not my choice to say, however, we&#8217;ll let that slide. So that&#8217;s sort of the research perspective.</p>
            <p>Another really, really obvious example is something like the Nintendo DS&#8217;s Brain Training. Wow! Were they surprised by that! Woo, golly! Nicole Kidman playing a DS? Johnny Ball, Zoe Ball, everybody&#8217;s playing DS! That&#8217;s one way that they&#8217;re starting to try and expand that and I think the impetus for that was the recognition that, while at the minute they&#8217;ve got a really fantastic audience of primarily between the ages of 14 to&#8230;I suppose it&#8217;s moving up to 30&#8230; the average age of an Xbox gamer is 28, for example &#8212; that sort of age range. They recognize that there&#8217;s a drop off that&#8217;s going to happen and that if they don&#8217;t adapt then not only will they not be able to get all that possible money but the money that they&#8217;re currently getting now will start to dwindle. I think that&#8217;s why the games industry.</p>
            <p>Has started to think about that.</p>
            <p>In terms of the web industry, I don&#8217;t know. I&#8217;m closer to the games industry, unfortunately &ndash; well, not unfortunately, but with reference to your question, obviously. Examples of how&#8230;.[pause] I&#8217;ll have to think about that and I&#8217;ll have to get back to you on that, Tom. Sorry. But, I might blog about it.</p>
        </blockquote>
        <blockquote class="speaker_3_text">
            <p><cite class="speaker_3" >Alex:</cite> Thank you very much!</p>
        </blockquote>
            
		  <p class="transcript_credit">Transcription by <a href="http://castingwords.com">CastingWords</a>, sponsored by <a href="http://www.opera.com">Opera</a>.</p>
	</div>

</div>


<?php include("../includes/footer.inc.php"); ?>