<?php 
	$title = "Joshua Porter";
	$section = "podcasts";
	include("../includes/header.inc.php"); 
?>

<div class="container clear">
	<div class="secondary">
		<ul class="speakers">
			<li><a href="/schedule/StevenJohnson.php" class="speak2">Steven Johnson</a></li>
			<li><a href="/schedule/AleksKrotoski.php" class="speak3">Aleks Krotoski</a></li>
			<li><a href="/schedule/DanielBurka.php" class="speak4">Daniel Burka</a></li>
			<li><a href="/schedule/MattJones.php" class="speak5">Matt Jones</a></li>
			<li><a href="/schedule/MattBiddulph.php" class="speak6">Matt Biddulph</a></li>
			<li><h2><a href="/schedule/JoshuaPorter.php" class="speak7">Joshua Porter</a></h2></li>
			<li><a href="/schedule/JeremyKeith.php" class="speak8">Jeremy Keith</a></li>
			<li><a href="/schedule/TantekCelik.php" class="speak9">Tantek Celik</a></li>
		</ul>
	</div>
	<div class="primary transcript">
	<h2>Leveraging Cognitive Bias in Social Design</h2>
		<p class="transcript_credit"><a href="http://opera.com"><img src="/img/sponsors/opera.gif" alt="Opera Software" /></a>
		Transcription sponsored by <a href="http://www.opera.com/">Opera</a>.</p>
		
		 <blockquote>
            <p> It&#8217;s an amazing honor to be introduced by the guy who taught me html. I don&#8217;t know if you guys know this, but back in the late 90&#8217;s Richard created a site called <a href="http://www.jalfrezi.com/">HTML Jalfrezi</a>. I was working, at the time, as an intern while I was at the University, as you say. A guy I worked with, his favorite site in the entire world was HTML Jalfrezi. And within a week or so my favorite site in the world was HTML Jalfrezi. So anyway, thank you, Richard, for helping me along.</p>
            <p>Very similar to Alex, I&#8217;m going to be talking about the merging of the web [technical problem] the merging of the web with social psychology. The difference is that I know very little about social psychology. But I&#8217;m going to try anyhow.</p>
            <p>What I found in working with clients and on really interesting social projects is that it&#8217;s a lot about psychology. I remember a couple years ago I met another American designer named Ryan Sims who works on a site called <a href="http://theverb.com/" >theverb.com</a>. I was asking him all these questions about how does it work, how was the interaction, because I was really interested in it at the time. We had both had a few beers and we talked for quite some time. And I remember this moment at the end of our discussion where we were like, web design is now about psychology. Web designers need to add these psychological principles to their toolkit in order to figure out how to provide the best interactive sequence in certain cases and how to provide engagement and stickiness.</p>
            <p>Since around that time, I&#8217;ve been trying to read more and more about social psychology. And everything I read is completely applicable to all the stuff that we&#8217;re all working on. But, again, the problem is that for some reason the worlds really haven&#8217;t collided. So my talk is an attempt to try to collide those worlds a little bit. So I&#8217;m going to be talking about leveraging cognitive bias in social design.</p>
            <p>We&#8217;ll start off with a question for you all. I want to get your opinion. I&#8217;m going to be showing you pictures of two different restaurants. And I want to know that if you were hungry and you were looking for a place to eat, which restaurant you would go to. OK. Here&#8217;s the first one. [pause] And here&#8217;s the second one. [pause] First one. [pause] Second one. [pause]</p>
            <p>OK. So now I&#8217;ll take a vote. Who would go to the first one? OK. Let&#8217;s say three or four percent of you. And who would go to this one? Everyone else, right? Some of the reasons why most of us would go to the second one is because the first one is pretty cold. There are several elements, which would be called design elements. For one thing, it&#8217;s kind of solid back here, kind of looks like a store front. It&#8217;s not really clear what type of restaurant it is. Also, there&#8217;s a very clear barrier here between actually the place you would sit down and eat and the place that you currently are. Now, the second one, you can walk right up to those tables.</p>
            <p>The first one, also has people walking by, they&#8217;re not paying attention to the restaurant. But most important of all, of course, is that there&#8217;s no one sitting down. And in the second one we see a lot of evidence of human activity. We have people in the windows, here, who are engaged. They&#8217;re talking with each other. And we have a line coming out the door. And it&#8217;s one of those lines that&#8217;s the perfect length, right. It shows that it&#8217;s worth going there. So people are kind of bunching in, but it&#8217;s not long enough to dissuade us from going unless we&#8217;re in a real hurry. So it&#8217;s not one of those nightclub lines that&#8217;s 100 people long.</p>
            <p>The point is that when we&#8217;re faced with making a decision, which I asked you guys to make a decision &#8212; we don&#8217;t know anything about those restaurants. We&#8217;re working on very limited information. The only information we have is the information that I showed you in the pictures. We use some sort of strategy to figure out which restaurant to go to.</p>
            <p>In social psychology circles, this is sometimes called the bandwagon effect. It&#8217;s often associated with acting like a sheep, behaving like a sheep. But that&#8217;s what we do. When we don&#8217;t know something, we follow the lead of others. The bandwagon effect is one of these ways, called a heuristic, that we made decisions based on limited data. So when we don&#8217;t know everything there is to know, we just use a shortcut.</p>
            <p>Here&#8217;s another example in depth. I love this video.</p>
            <p>[<a href="http://www.metacafe.com/watch/914321/elevator_candid_must_see/">video</a>]</p>
            <p>&quot;The gentleman in the elevator now is a Candid star. These folks who are entering, the man with the white shirt, the lady with the trench coat, and subsequently one of the members of our staff, will face the rear. And you&#8217;ll see how this man in the trench coat [laughter] tries to maintain his individuality. But little by little [laughter] he looks at his watch, but he&#8217;s really making an excuse for turning just a little bit more to the wall.&quot;</p>
            <p>&quot;Now we&#8217;ll try it once again. Here&#8217;s the Candid subject. Here comes the Candid Camera staff, three of them at least. And this man has apparently been in groups before [laughter]. &quot;</p>
            <p>&quot;Here&#8217;s a fellow with his hat on in the elevator. First he makes a full turn to the rear, and Charlie closes the door. A moment later, we&#8217;ll open the door. Everybody&#8217;s changed positions. [laughter]&quot;</p>
            <p>&quot;Now we&#8217;ll see if we can use group pressure for some good. In a moment, on Charlie&#8217;s signal, everybody turns forward. Notice they take off their hats. [laughter] And now do you think we could reverse the procedure? Watch. [laughter]&quot;</p>
            <p>[video playing] </p>

            <p> So we follow the behavior of others and it&#8217;s called a heuristic. What we normally think of when we think of rational behavior would be that you explore all your options, you find out as much information as you can, and then you make a very disciplined decision based on that information.</p>
            <p>But a heuristic, something like the bandwagon effect, is when we just take a shortcut and we say, &quot;You know what? I don&#8217;t know anything about the restaurants,&quot; or &quot;I don&#8217;t know how to stand in this elevator and I&#8217;m just going to follow what other people are doing for lack of a better strategy.&quot;</p>
            <p>But the thing with heuristics is that they have a complement called cognitive bias, which is when those shortcuts don&#8217;t turn out all that well and they actually don&#8217;t work. In some cases, those heuristics that we use lead to very predictable outcomes and these predictable outcomes, the biases, affect all of us, even when we know about them, which is the fascinating part.</p>
            <p>Here are some examples of biases that are directly related to the design profession. One of my favorites is the Lake Wobegon effect, where everybody is above average &ndash; everybody thinks they&#8217;re above average.</p>
            <p>But you&#8217;ll notice we have things like the &quot;not invented here&quot; bias, which affects a tremendous number of software developers and designers who don&#8217;t want to&#8230; for anything they can do, they don&#8217;t want to use someone else&#8217;s ideas or someone else has invented something really good and they just refuse to use it because it didn&#8217;t come from where they are.</p>
            <p>And, of course, the last one &ndash; I&#8217;m sure none of us have ever had this problem: the tendency to underestimate the time and cost of work. And even though we know better, we&#8217;ve done it for years, we still underestimate the time and cost of work.</p>
            <p>This whole idea of heuristics and biases came out of a seminal paper written in 1974 by Daniel Kahneman and Amos Tversky. Since then, a tremendous amount of research in the social psychology field has been based on these ideas. In fact, I believe it was in 2003 or so, they won a Nobel Prize for the work that they did.</p>
            <p>So now I have another question for you as we get into how this relates to design. I think that designers can really take advantage of some of these ideas in the way that they design screens and the way that they write copy. So that&#8217;s what I&#8217;m going to be talking about.</p>
            <p>So read on this. This describes Linda, who&#8217;s a 31-year-old, very bright woman. And this question is from one of the studies that Kahneman and Tversky did. They asked people this question, OK?</p>
            <p>In terms of bias, you folks are all bias in the sense that you know I&#8217;m talking about heuristics and biases. The people who were getting this test thought it was just some study of some other sort, so they weren&#8217;t ready to be surprised in any way and they weren&#8217;t going to see what the answer is.</p>
            <p>So our initial idea&#8230; a lot of us would be drawn, actually, to the second answer here because all the description that we have in the first paragraph talks about traits that we might associate with someone in the feminist movement, right? And that&#8217;s the whole point of the question.</p>
            <p>But, strictly speaking &ndash; and I won&#8217;t ask you to raise your hands for this one &ndash; but, strictly speaking, the group of people who are bank tellers always has to be bigger than the group of people who are bank tellers and feminists. So the correct answer here is &ndash; the thing that&#8217;s more likely &ndash; is that Linda is a bank teller.</p>
            <p>So this is one of the classic questions from Kahneman and Tversky in that in one of their studies, about 90% of respondents chose the middle one when that actually cannot be the case. Now some of you might be thinking, &quot;Well, people were interpreting the question to mean &ndash; the first option &ndash; to mean Linda is a bank teller and not in the feminist movement.&quot;</p>
            <p>But that&#8217;s actually a big concern that the researchers had. And I don&#8217;t know all the details of their other research, but essentially they ruled that out over time by doing a lot of follow-up studies.</p>
            <p>OK, let&#8217;s talk about how this starts to relate to design. So this is an example of representation bias &ndash; that as the amount of detail in a scenario increases, the probability of it actually happening declines really quickly because the more and more specific you get, the less and less likely that is to be the general case.</p>
            <p>So here&#8217;s an example of an interface from the site <a href="http://freshbooks.com/" >FreshBooks.com</a>. And what they&#8217;ve done &ndash; and I think this is a brilliant piece of interface design &ndash; is that they are showing people who use their software. It&#8217;s an invoicing and billing software. This is just one part of the page and what they&#8217;re doing is they&#8217;re showing people who are representative users.</p>
            <p>Now these people look at all their details. These details probably resonate with you folks in relatively strong ways &ndash; design studio project manager editor &ndash; because this is the audience that they&#8217;re going after. So what they&#8217;ve done is they&#8217;ve really leveraged the idea of representativeness and put in all those details that will resonate with their exact audience.</p>
            <p>And they do some really interesting things. They have authentic photos. So, on a lot of sites, you see these nice stock photos of people that are really well lit and everyone&#8217;s smiling and everything. But it&#8217;s just not authentic.</p>
            <p>But these guys have done a really good job having authentic photos. They even do things like show team sides, which I think is a really nice touch because it&#8217;s really speaking to their audience. Now, these people might not be representative of the rest of the people who use their software.</p>
            <p>But as an interface design tactic, if that&#8217;s the audience you&#8217;re aiming at, it really makes sense to dive into those details because as people read those details, that bias will kind of click into effect. And if the details happen to be details that people resonate with, then they&#8217;ll be much more likely to like the software.</p>
            <p>Here&#8217;s another example on <a href="http://yelp.com/" >Yelp.com</a>. They have a feature called &quot;Review of the Day&quot; down here on the right. And every time I&#8217;ve ever clicked on that feature, the person in that feature, you get something like this: you get one of the site&#8217;s most wonderful and engaged users. They have a lot of friends. They have a bunch of firsts, which means they were the first people to review a certain service. They have a whole bunch of things going on. They&#8217;ve done a whole bunch of reviews. She&#8217;s got 182 reviews or 192 reviews. She&#8217;s essentially a power user.</p>
            <p>So what Yelp is doing is by showing these people on the home page of the site, they&#8217;re showing the desired behavior of people within the system. So people who are new to Yelp and they come and say, &quot;Oh, that&#8217;s the type of behavior that is valued here at <a href="http://yelp.com/" >Yelp.com</a>. That&#8217;s the representative user.&quot; When, in fact, it&#8217;s not the representative user.</p>
            <p>If you start clicking on a whole bunch of people, you go through a whole bunch of folks on the site, you actually come away with the feeling that &quot;Whoa, there&#8217;s a lot of people who don&#8217;t do much at all on this site.&quot; But those aren&#8217;t the people who make the home page.</p>
            <p>So here&#8217;s another question for you. Would you accept this bet, OK? A 50% chance of gaining a 100 pounds or a 50% chance of losing a 100 pounds. How many would accept this bet?</p>
            <p>One person. OK, there&#8217;s a couple in the back. Probability wise its 50%. So why not, right? How about 200 pounds? OK, a couple more. 300 pounds? OK. Well, I should have gone higher that&#8217;s as high as my slide goes.</p>
            <p>So it&#8217;s been shown in many studies&#8230;of course, probability wise it&#8217;s the same. The first one is 50% chance of gaining and losing. But the thing is there is a thing called loss aversion. And people, when they are making decisions about money and other things, losses loom much larger than gains.</p>
            <p>So the first bet, right. You could actually have won a 100 pounds. And nobody tried to do it. It was a 50% chance. Well, two or three were willing to do it. I mean that&#8217;s really something. So again, this is a bias that affects everyone. It would affect people if we went to Asia and asked the same question. And it would affect people if we went to Africa and asked the same question &ndash; North or South America. It affects everybody the same.</p>
            <p>I think we can leverage this as well if we talk about &ndash; similar to what Alex was saying about when people start adding content to the sites and starting to get engaged. If we frame that stuff in terms of a loss, for example on Netvibes, you go to the website and you can play around in the website. They have a really cool instant engagement thing where you can start using widgets and stuff.</p>
            <p>Well, in the top right hand corner they have these texts &quot;Not a member yet, register now to save your page&quot;. &quot;Oh! Wow. You mean it&#8217;s not saved. I have to do something to save it. I might lose it.&quot; So they are starting to kind of go down the road of framing it as a loss. They could word this in another ways.</p>
            <p>Here&#8217;s another example from Chimp, which is the project I am currently ensconced in. I&#8217;m going to show you two examples of bit of interface that I worked on. This is a feature described in terms of gain. OK, so we were talking about OpenID. When you sign up for the site you get an OpenID that you can use on a whole bunch of other sites.</p>
            <p>So, the idea is that you can now log into a whole bunch of other sites. That&#8217;s a benefit that&#8217;s part of the system. This is one of the versions. But here&#8217;s the same feature described in terms of a loss. So don&#8217;t forget another password. This resonates a lot more with people because they know the pain of losing, and they really want to prevent that. So just changing this copy &ndash; it was just a copy change in this case &ndash; makes that much more effective.</p>
            <p>So here&#8217;s another example. This is actually a wonderful feature on Best Buy. It&#8217;s an e-commerce electronics retailer, so they sell TVs and all that stuff. When you are shopping on Best Buy and you get to the check out moment, they don&#8217;t make you sign up for an account. They can say &quot;Check out without creating an account,&quot; which is great.</p>
            <p>In fact, just that feature alone improves conversion by almost 20%. So this is the feature you need on the other end, right. You still want people to create an account, because it&#8217;s in Best Buy&#8217;s best interest to have people create an account. But it&#8217;s also in the best interest of the person shopping. But they talk about &#8212; they mostly frame this around in terms of future savings, right. So save time the next time you shop. But people don&#8217;t really deal with future saving all that strongly. But what they do because of the loss aversion&#8230; I wonder if this could be redesigned and framed more effectively as an immediate loss.</p>
            <p>So, what if instead of, it saves time the next time you shop, it was something like, don&#8217;t lose the ability to track your package. Or, if you don&#8217;t sign up now you won&#8217;t be able to track this package or something like that.</p>
            <p>OK, here&#8217;s another question for you. What is more valuable to you, any old coffee mug down at the convenient store or one that your loved one gave you? My guess is that most of us would choose &#8216;b&#8217;. Because it has sentimental value, it means something to us. But the reality is that in a marketplace they are actually worth the same thing, right.</p>
            <p>But, this is an example of ownership bias. That when we own something, when it comes into our purview, we feel like it&#8217;s more valuable.</p>
            <p>Social psychologists have done really interesting studies, where they&#8217;ve literary asked people &ndash; so there&#8217;s a coffee cup on the table. And they say, &quot;How much would you pay for that coffee cup?&quot; And people say, &quot;A buck.&quot; And then they do another set of tests, where, when everyone enters the room they give them a coffee cup, and then at some point later in the day they put that coffee cup on the table, and they say &quot;That&#8217;s your coffee cup. How much would you sell that for?&quot;</p>
            <p>And they say invariably like &quot;Three or four dollars.&quot; And it&#8217;s just a coffee cup they got that day.</p>
            <p>And again these things have been tested over, over and over in all sorts of cultures, and they really are consistent. So, here&#8217;s just a simple example of ownership. You know, YouTube is all about me. MySpace is all about me. I happen to be staying in a place called My Hotel. I kind of feel like it&#8217;s my place, you know.</p>
            <p>So these are just subtle ways of changing copy, or completely branding your startup &#8212; to talk about ownership, and to convey the idea of ownership. Here&#8217;s a great example. Flickr is just littered with &quot;you&quot; and &quot;your stuff&quot;. And so everything about the site, you can&#8217;t go there without thinking, &quot;This is all my stuff and I own it.&quot; And it probably doesn&#8217;t make the entire difference between using the system and not. But it gives the sense of ownership. I think that&#8217;s very applicable in a lot of cases.</p>
            <p>OK, so, here&#8217;s a really, really interesting problem &ndash; the sign up problem. It&#8217;s the product adoption problem. A lot of us are working on projects where we need more and more people to use it. Maybe we are working on a startup where we want to drive adoption of our product or we are working on an existing system and we want to grow our user base.</p>
            <p>But the thing is that people can only use so much software. Let me think. I think I have like 20 or 30 applications that I use all the time that are my favorite pieces of software. And yet there are thousands of applications being released all the time. Why am I not trying new stuff? Why am I not switching? Why am I not at least taking the time to see if they offer more?</p>
            <p>Well, all these biases kind of work together to prevent me from doing that. For one, I have ownership bias. So I bought my copy of Super Duper, and I paid $30 for it, or however much it is now, $40; I don&#8217;t know. And I own it. So I&#8217;m not going to give that up very easily. So anybody else who&#8217;s offering something similar is going to have to do a heck of a lot more than offer a competing service. They&#8217;re going to have to do way more than that. So the people like us, who use software all the time, we value it a lot. Everybody values the software a lot. In fact, because of the ownership bias, and because of loss aversion, we value it approximately three times more than is rational.</p>
            <p>There&#8217;s a wonderful paper in the June 2006 Harvard Business Review, called &quot;Eager Sellers and Stony Buyers,&quot; which kind of blew my mind when I read it, because it very clearly talked about how all these cognitive biases are a huge impediment to product adoption. And all of us working on product adoption: we&#8217;re not just trying to climb this little hill; we don&#8217;t just have to go out and convince somebody. We have to really knock them over the head with a sledgehammer to get them to use our product.</p>
            <p>So potential buyers or potential users are biased to keep what they have. The really interesting thing is that, on the other side, on the software makers&#8217; side, they&#8217;re biased as well, right? So they&#8217;re biased because they own this project, it&#8217;s their project, it&#8217;s their baby, it&#8217;s their piece of software, and they&#8217;re really proud of it. But there&#8217;s also the optimism bias that was on that list earlier, where most people are, by nature, optimistic for the future: we envision the future as better than the past, when, in fact, it all averages out. So, because of various biases on the software makers&#8217; side, they actually overvalue software that they&#8217;re offering by about three times. And the author of this piece, who came up with this model, basically looked at a whole bunch of wide-ranging research, and in some cases people valued stuff two times more and in some cases it was four more, so he kind of simplified it and said it&#8217;s about three times more.</p>
            <p>But the net effect is that there&#8217;s a nine-times disparity between the person who is the potential user of the software and the person who&#8217;s offering the software. So there&#8217;s this huge gulf between the desire of the potential user and desire of the person offering the software.</p>
            <p>So, for web designers, in this day and age, when there&#8217;s thousands of pieces of software being shipped every day, the novelty has kind of worn off, in the sense that you just don&#8217;t go out and try everything. We&#8217;re here to do work on the web, so, as long as Super Duper is working for me, I just don&#8217;t have time to try anything else.</p>
            <p>So the sign-up problem, I believe, is one of the largest problems. The initial product adoption is one of the largest problems facing almost every web-design team in this day and age. So, I think, looking at it from this standpoint, at least we know what we&#8217;re kind of dealing with. It&#8217;s a huge barrier.</p>
            <p>So what can we do, from a design standpoint, to push back at this? So here&#8217;s an example of Slide. Slide is a widget-maker for social networks, Facebook and MySpace. And one of the things they do is they instantly engage you into making something. So, if you ever click on a Slide widget, this is something similar to what you&#8217;ll get. You put a photo in the top left; you add a bunch of images. There&#8217;s no sign-up here; sign-up&#8217;s been deferred. You just make something, and you own it. You make something. The act of making something signals ownership: if I make something, I own it. Well, there are large record companies and large interests that don&#8217;t believe that, social networks who take your information when you put it on there. But the point is that the act of doing it creates this feeling of ownership. So Slide, I think that&#8217;s a great example of instant engagement, instant feeling of ownership.</p>
            <p>Another example, a very popular example: Genie. It gets you started, you create your family tree almost immediately; you own it.</p>
            <p>My favorite example, which I&#8217;ll end with, is back to Freshbooks, which I showed to those folks earlier. If you&#8217;re looking to design a sign-up page, you definitely have to check out Freshbooks. They use almost every sign-up tactic that I&#8217;ve seen on their home page. And I think they do a great job. I know they test the page a lot.</p>
            <p>But let&#8217;s just go through some of the things that, I think, really kind of leverage all of those biases that could possible crop up. They have &quot;Try It for Free&quot;. You can sign up for free. They show a little bit of that bandwagon stuff: there&#8217;s 300, 000 new users. They have Features and Benefits, so if people want to read and check out the benefits, they can do that. Why is this better than the product that you&#8217;re currently using? That&#8217;s what they&#8217;re really getting at there. Of course, I failed to mention that they explain exactly what it is, right off the bat, which is, for some reason, a hard problem for some designs.</p>
            <p>They also offer a telephone number, which I think is a great idea, right there if you have any questions. One of the things, I talked a little bit with Mike McDermott, their CEO, and he said that, as they&#8217;re growing over time, they&#8217;re getting into a bigger and bigger company, so that telephone number really made a lot of sense to keep really prominent, because people aren&#8217;t deciding just to use this for themselves. but for larger companies.</p>
            <p>So then they have a whole bunch of bits down here. &quot;Some of Our Happy Users.&quot; I already talked about that. &quot;Who Uses Freshbooks?&quot; &quot;Where Is Freshbooks Used?&quot; I love that graphic. And that really gives you the restaurant sense, that there&#8217;s people in line here, that there&#8217;s people using this thing. And then they also have feedback from users, which is really, really cool: &quot;What Our Users Report.&quot;</p>
            <p>And then they just keep going. &quot;More Happy Users,&quot; so now they have more quotes from people. Continuing down the line, down to the bottom of the page, there&#8217;s just a bunch of quotes. They&#8217;ve highlighted the nice bit.</p>
            <p>So I think that, as Alex was saying, from an academic standpoint, it helps to have a model to think about the stuff a lot of the time. I&#8217;ve found this sort of stuff really invaluable when I&#8217;m talking to people whom I need to convince of something, like &quot;I think we should probably do it this way; maybe we should frame it as a loss instead of a gain, because losses loom larger.&quot; From little things, like copywriting, to larger things, like sign-up and entire pages.</p>
            <p>So, if I had to guess for the future, I think we&#8217;re going to see more and more crossover from industries like gaming, from academic circles like social psychology. Just more and more of how to inform our design and really how to deal with irrational people, basically.</p>
            <p>So, anyway, thank you.</p>
            <p>We have time for questions, don&#8217;t we? Five minutes? OK. I&#8217;m not going to take any questions from you, Alex. You&#8217;re a social psychologist. </p>
        </blockquote>
        <blockquote class="speaker_2_text"> 
            <p><cite class="speaker_2">Man 1:</cite> Hi. Isn&#8217;t this evil?</p>
            <p>[laughter] </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3">Joshua:</cite> I&#8217;m sorry? </p>
        </blockquote>
        <blockquote class="speaker_4_text">
            <p><cite class="speaker_4">Man 2:</cite> Isn&#8217;t this evil? </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3">Joshua:</cite> Is this evil? </p>
        </blockquote>
        <blockquote class="speaker_4_text">
            <p><cite class="speaker_4" >Man 2:</cite> Aren&#8217;t you trying to mislead people to do things that they don&#8217;t want to do? </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3">Joshua:</cite> Is this evil? You mean, is it like manipulating? </p>
        </blockquote>
        <blockquote class="speaker_4_text">
            <p><cite class="speaker_4">Man 2:</cite> Yeah. </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3">Joshua:</cite> Well, absolutely. </p>
        </blockquote>
        <blockquote class="speaker_4_text">
            <p><cite class="speaker_4">Man 2:</cite> Oh. </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3">Joshua:</cite> That&#8217;s a great question. I think, if your business ethics are in the right place, if your heart&#8217;s in the right place, dealing as a business, then it&#8217;s not unethical that you&#8217;re, you know, you&#8217;re trying to provide a win-win. Say you&#8217;re offering a piece of software that &ndash; you&#8217;re really frustrated with what&#8217;s out there, and you really do provide a better solution, that&#8217;s what innovation is: you&#8217;re, in theory, making the world a better place.</p>
            <p>To your point, though. Getting into psychology is everything they do at casinos and everything, and they really do manipulate people. And, even sometimes when we know it &ndash; you go to a casino, for example, and everything&#8217;s built around the social psychology of it all, but yet people still sign up for these cards that they take around. And they know the casino can track everything they do; and the casino essentially can game the system in any way they want, to keep them coming back. I don&#8217;t know. That&#8217;s really where the thing is with cognitive bias: even when we&#8217;re aware of it, we&#8217;re still susceptible to it. So, whether or not it&#8217;s evil, we&#8217;re going to fall for it in some way.</p>
            <p>But I think the question is more about business ethics. If your business is ethical, then the way you sell your business can be ethical, too.</p>
            <p>I was kidding, by the way. I will take your question. Yes. </p>
        </blockquote>
        <blockquote class="speaker_4_text">
            <p><cite class="speaker_4">Man 2:</cite> You mentioned earlier a couple of metrics, one of which was checkout without account sign-up. You said it increases sales by 20 percent. Where&#8217;s that from? Twenty percent would be great for me.</p>
            <p>[laughter] </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3">Joshua:</cite> Yeah. Well, I&#8217;m not at liberty to say who the client was, but it was for a major U.S. e-commerce retailer. In fact, it&#8217;s about between 10 and 20 percent. On several projects in the job that I worked on last, when shoppers were given an option to check out without doing registration, it increased sales. Yes? </p>
        </blockquote>
        <blockquote class="speaker_5_text"> 
            <p><cite class="speaker_5">Woman 1:</cite> Hi. I&#8217;m not going to hurt you, I promise. You say that a lot of the biases are international. And I feel it&#8217;s quite safe to say that not all sites work internationally. And I&#8217;m wondering if there&#8217;s anything that you can say, doesn&#8217;t work internationally, from this point of view. So say observation bias works and all those types of things. What doesn&#8217;t work internationally? What wouldn&#8217;t work in the UK or in China or somewhere? </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3">Joshua:</cite> OK; that&#8217;s a great question. I have absolutely no idea.</p>
            <p>[laughter] </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3">Joshua:</cite> Yes. In my next talk, I&#8217;ll work some of that in. Any other questions? Easy question?</p>
            <p>[laughter] </p>
        </blockquote>
        <blockquote class="speaker_6_text"> 
            <p><cite class="speaker_6">Man 3:</cite> Well, actually, it&#8217;s more of a follow-up, in terms of international applicability or whatever. I think that stuff like YouTube or MySpace might be less applicable to collectivity-oriented societies, like Asian societies, whereas Western societies are more individualistic. So maybe that kind of goes in that direction. </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3">Joshua:</cite> Yeah, that&#8217;s a great point. And, now that you mention it, I do remember reading that it&#8217;s mostly about strength of bias in different societies. As you say, in some societies, biases will be much stronger, so the ownership bias might be much stronger in some societies than in others. Yes? </p>
        </blockquote>
        <blockquote class="speaker_7_text">
            <p><cite class="speaker_7">Man 4:</cite> How do you reconcile something like Freshbooks, which, to me, looked like a direct-marketing pitch that I might receive in my mail and toss into the trash, something from Time magazine perhaps, with the success of something like Slide, which, although it uses some similar tricks, seems to be a lot less full-on. Is there, for want of a better word, a heuristic to actually say, &quot;When have you gone to far with using these sorts of tricks?&quot; </p>
        </blockquote>
        <blockquote class="speaker_3_text"> 
            <p><cite class="speaker_3">Joshua:</cite> When have you gone too far? I think there is a danger of trying to automate too much. If you get people started and they actually don&#8217;t know what&#8217;s going on and they actually don&#8217;t know that they&#8217;re building a widget for Slide, that&#8217;s certainly an issue. But really that&#8217;s a contextual question. Every single application is going to be different. Freshbooks is even going to be different than their competitors, because they have perhaps a different interaction sequence or they get people started differently.</p>
            <p>We were talking, in the workshop that we had yesterday, about how some sites actually get you started instantly, so, instead of having a form to sign up, they&#8217;ll do like Netvibes did and you&#8217;ll just start instantly. And I think there is a trade-off, that, in some cases, a screen actually describing what the heck&#8217;s going on is more valuable.</p>
            <p>And one of the other things that Gorville mentioned &#8212; that piece that I mentioned from the Harvard Business Review &#8212; actually, I&#8217;m applying it to design, so I&#8217;ll paraphrase what he was saying. What most designers don&#8217;t think about is the behavior change we&#8217;re asking for when we&#8217;re introducing a new product. So we&#8217;re not just saying, &quot;We want you to sign up for our piece of software,&quot; we&#8217;re saying &quot;Oh, yeah, remember that habit that you have of using that other piece of software every day for the last five years? Yeah, we don&#8217;t want you to do that anymore.&quot; That&#8217;s a huge behavior change. So, in terms of behavior change, you want to minimize that as much as possible.</p>
            <p>I read an interesting piece talking about how Google was so successful because they didn&#8217;t make you change your behavior. You just kept typing in a query, like you do with a different site. But the flip side is that, when a new, better search engine comes along, they&#8217;ll probably just have the exact same query box. So it really is a difficult thing and it&#8217;s very contextual. I guess that&#8217;s my answer for that one.</p>
            <p>Do we have any other questions?</p>
            <p>OK. I&#8217;m not going to stand in the way of your food, so let&#8217;s eat.</p>
        </blockquote>
            
		  <p class="transcript_credit">Transcription by <a href="http://castingwords.com">CastingWords</a>, sponsored by <a href="http://www.opera.com">Opera</a>.</p>
	</div>

</div>



<?php include("../includes/footer.inc.php"); ?>